/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_prompt_templates"];
        put?: never;
        post: operations["create_prompt_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/prompts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_prompt_template"];
        put?: never;
        post?: never;
        delete: operations["delete_prompt_template"];
        options?: never;
        head?: never;
        patch: operations["update_prompt_template"];
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["chat_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_config"];
        trace?: never;
    };
    "/api/config/ui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_ui_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["plan_load"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/load/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["execute_load"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontologies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_ontologies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["export_ontology"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/export/cypher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["export_cypher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/export/graphql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["export_graphql"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/export/mermaid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["export_mermaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/export/owl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["export_owl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/export/python": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["export_python"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/export/shacl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["export_shacl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/export/typescript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["export_typescript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/import/owl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["import_owl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/normalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["normalize_ontology"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perspectives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["save_perspective"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perspectives/by-lineage/{lineage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_perspectives"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perspectives/by-lineage/{lineage_id}/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 2-tier perspective lookup: exact lineage match, then topology match. */
        get: operations["get_best_perspective"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perspectives/by-lineage/{lineage_id}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_default_perspective"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perspectives/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_perspective"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_pins"];
        put?: never;
        post: operations["create_pin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_pin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_projects"];
        put?: never;
        post: operations["create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_project"];
        put?: never;
        post?: never;
        delete: operations["delete_project"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/apply-reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["apply_reconcile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_decisions"];
        trace?: never;
    };
    "/api/projects/{id}/design": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["design_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/design/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["design_project_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["edit_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["extend_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/ontology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["apply_ontology_commands"];
        trace?: never;
    };
    "/api/projects/{id}/reanalyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reanalyze_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refine_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/refine/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refine_project_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_revisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/revisions/{rev}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_revision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/revisions/{rev}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restore_revision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_prompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query/from-ir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["execute_from_ir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_executions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_execution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["raw_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatStreamRequest: {
            execution_mode?: string | null;
            message: string;
            /** @description Override the LLM model for this request (e.g., "claude-opus-4-6"). */
            model_override?: string | null;
            ontology: Record<string, never>;
            /** Format: uuid */
            project_id?: string | null;
            /** Format: int32 */
            project_revision?: number | null;
            /** Format: uuid */
            saved_ontology_id?: string | null;
            session_id?: string | null;
        };
        ConfigEntry: {
            data_type: string;
            description: string;
            key: string;
            value: string;
        };
        ConfigUpdate: {
            category: string;
            key: string;
            value: string;
        };
        ConfigUpdateRequest: {
            updates: components["schemas"]["ConfigUpdate"][];
        };
        CreateProjectRequest: Record<string, never> & {
            title?: string | null;
        };
        /** @description Cursor-based pagination parameters. */
        CursorParams: {
            /** @description Opaque cursor from a previous response's `next_cursor` */
            cursor?: string | null;
            /**
             * Format: int32
             * @description Max items to return (default 50, max 100)
             */
            limit?: number | null;
        };
        /** @description Design project — ontology design lifecycle. */
        DesignProject: {
            analysis_report?: unknown;
            /** Format: date-time */
            analyzed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            design_options: unknown;
            /** Format: uuid */
            id: string;
            ontology?: unknown;
            quality_report?: unknown;
            /** Format: int32 */
            revision: number;
            /** Format: uuid */
            saved_ontology_id?: string | null;
            source_config: unknown;
            source_data?: string | null;
            source_history: unknown;
            source_mapping?: unknown;
            source_profile?: unknown;
            source_schema?: unknown;
            status: string;
            title?: string | null;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
        };
        /** @description Design project summary (lightweight, for list endpoints). */
        DesignProjectSummary: {
            /** Format: date-time */
            analyzed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            revision: number;
            /** Format: uuid */
            saved_ontology_id?: string | null;
            source_config: unknown;
            status: string;
            title?: string | null;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
        };
        ErrorBody: {
            /** @description Optional additional details */
            details?: unknown;
            /** @description Human-readable error message */
            message: string;
            /** @description Machine-readable error type (e.g., "not_found", "bad_request") */
            type: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        ExecuteFromIrRequest: {
            /** @description Optional ontology ID for context (used during deserialization). */
            ontology_lineage_id?: string | null;
            /** @description The QueryIR to compile and execute. */
            query_ir: Record<string, never>;
        };
        ExecuteFromIrResponse: {
            /** @description The compiled query statement in the target language. */
            compiled_query: string;
            /** @description The compilation target (e.g. "cypher"). */
            compiled_target: string;
            /** @description Query result rows and metadata. */
            result: Record<string, never>;
            /** @description Widget hint for optimal result visualization. */
            widget_hint?: unknown;
        };
        LoadExecuteRequest: {
            /** @description Data batches to load. Each element is a JSON object representing one record. */
            data: unknown[];
            /** @description OntologyIR for the target graph schema. */
            ontology: Record<string, never>;
            /** @description Optional pre-computed load plan. If omitted, the plan is generated via LLM. */
            plan?: Record<string, never> | null;
            /** @description Description of the data source. */
            source_description: string;
        };
        LoadExecuteResponse: {
            /** @description Compiled statements executed. */
            compiled_statements: string[];
            /** @description Load plan used. */
            plan: Record<string, never>;
            /** @description Execution results. */
            result: Record<string, never>;
            /** @description Compiler target language. */
            target: string;
        };
        LoadPlanRequest: {
            /** @description OntologyIR for the target graph schema. */
            ontology: Record<string, never>;
            /** @description Description of the data source for the LLM. */
            source_description: string;
        };
        LoadPlanResponse: {
            /** @description Compiled statements in the target language. */
            compiled_statements: string[];
            /** @description Generated load plan. */
            plan: Record<string, never>;
            /** @description Compiler target language (e.g., "cypher"). */
            target: string;
        };
        OntologyCommandsRequest: {
            /** @description List of ontology mutation commands. */
            commands: Record<string, never>[];
            /** Format: int32 */
            revision: number;
        };
        OntologyCommandsResponse: {
            project: Record<string, never>;
        };
        OntologyImportRequest: {
            /** @description OWL ontology in Turtle format. */
            content: string;
        };
        /** @description Ontology revision snapshot. */
        OntologySnapshot: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            ontology: unknown;
            /** Format: uuid */
            project_id: string;
            quality_report?: unknown;
            /** Format: int32 */
            revision: number;
            source_mapping?: unknown;
        };
        /** @description Ontology revision snapshot summary (lightweight). */
        OntologySnapshotSummary: {
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            edge_count: number;
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            node_count: number;
            /** Format: int32 */
            revision: number;
        };
        /**
         * @description Cursor-based pagination metadata.
         *
         *     Carries the opaque cursor used to fetch the next page of a
         *     cursor-paginated list endpoint. Surfaces in OpenAPI under
         *     `components.schemas.PageMeta`; list-handler responses include this
         *     inside the universal `ApiResponse` envelope.
         */
        PageMeta: {
            /** @description Opaque cursor for the next page. `None` when this is the last page. */
            next_cursor?: string | null;
        };
        PerspectiveFindParams: {
            topology_signature: string;
        };
        PerspectiveUpsertRequest: {
            /** @description Collapsed group settings JSON. */
            collapsed_groups?: unknown;
            /** @description Filter settings JSON. */
            filters?: unknown;
            is_default?: boolean;
            lineage_id: string;
            name: string;
            /** @description Node positions JSON. */
            positions: unknown;
            /** Format: uuid */
            project_id?: string | null;
            topology_signature: string;
            /** @description Viewport state JSON. */
            viewport: unknown;
        };
        PinCreateRequest: {
            /** Format: uuid */
            query_execution_id: string;
            title?: string | null;
            /** @description Widget specification JSON. */
            widget_spec: unknown;
        };
        /** @description Pinboard item — a saved query result. */
        PinboardItem: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            pinned_at: string;
            /** Format: uuid */
            query_execution_id: string;
            title?: string | null;
            user_id: string;
            widget_spec: unknown;
        };
        ProjectCompleteRequest: {
            /**
             * @description Must be set to true if the quality report has low confidence or high-severity gaps.
             *     Prevents accidental promotion of low-quality ontologies.
             */
            acknowledge_quality_risks?: boolean;
            description?: string | null;
            /** @description Name for the saved ontology. */
            name: string;
            /** Format: int32 */
            revision: number;
        };
        ProjectDesignRequest: {
            /** @description Must be set to true if the schema has >100 tables and the user wants to proceed anyway. */
            acknowledge_large_schema?: boolean;
            /** @description Domain hints for the LLM. */
            context?: string;
            /** Format: int32 */
            revision: number;
        };
        ProjectDesignResponse: {
            project: Record<string, never>;
        };
        ProjectEditRequest: {
            /** @description If true, returns generated commands without applying them. */
            dry_run?: boolean;
            /** Format: int32 */
            revision: number;
            /** @description Natural language description of the desired ontology change. */
            user_request: string;
        };
        ProjectEditResponse: {
            /** @description Generated ontology mutation commands. */
            commands: Record<string, never>[];
            /** @description LLM explanation of what was changed and why. */
            explanation: string;
            /** @description Updated project (null in dry_run mode). */
            project?: Record<string, never> | null;
        };
        ProjectExtendRequest: {
            /** Format: int32 */
            revision: number;
            /** @description New data source to merge into the project. */
            source: components["schemas"]["ProjectSource"];
        };
        ProjectExtendResponse: {
            project: Record<string, never>;
            /** @description Report on ID reconciliation between existing and new ontology entities. */
            reconcile_report: Record<string, never>;
        };
        ProjectOrigin: {
            /** @enum {string} */
            origin_type: "source";
            repo_source?: Record<string, never> | null;
            source: components["schemas"]["ProjectSource"];
        } | {
            /** Format: uuid */
            base_saved_ontology_id: string;
            /** @enum {string} */
            origin_type: "base_ontology";
        };
        ProjectReanalyzeRequest: {
            /** @description Optional repository source for enrichment. */
            repo_source?: Record<string, never> | null;
            /** Format: int32 */
            revision: number;
            /** @description Data source to re-analyze (must match original source type). */
            source: components["schemas"]["ProjectSource"];
        };
        ProjectReanalyzeResponse: {
            /** @description Design decisions that were invalidated by the schema change. */
            invalidated_decisions?: string[];
            project: Record<string, never>;
        };
        ProjectReconcileRequest: {
            /** @description User accept/reject decisions for uncertain matches. */
            decisions: Record<string, never>[];
            /** @description Reconciled ontology with user decisions applied. */
            reconciled_ontology: Record<string, never>;
            /** Format: int32 */
            revision: number;
            /** @description The uncertain matches being decided upon. */
            uncertain_matches: Record<string, never>[];
        };
        ProjectRefineRequest: {
            /** @description Additional context for the LLM refinement. */
            additional_context?: string | null;
            /** Format: int32 */
            revision: number;
        };
        ProjectRefineResponse: {
            /** @description Summary of graph profiling results. */
            profile_summary: string;
            project: Record<string, never>;
            /** @description Report on ID reconciliation between original and refined ontology. */
            reconcile_report: Record<string, never>;
        };
        ProjectRestoreResponse: {
            project: Record<string, never>;
        };
        ProjectSource: {
            data: string;
            /** @enum {string} */
            type: "text";
        } | {
            data: string;
            /** @enum {string} */
            type: "csv";
        } | {
            data: string;
            /** @enum {string} */
            type: "json";
        } | {
            connection_string: string;
            schema?: string;
            /** @enum {string} */
            type: "postgresql";
        } | {
            connection_string: string;
            /** @description MySQL "schema" is the database name */
            schema: string;
            /** @enum {string} */
            type: "mysql";
        } | {
            connection_string: string;
            /** @description MongoDB database name */
            database: string;
            /** @enum {string} */
            type: "mongodb";
        } | {
            /** @description Snowflake account identifier (e.g., `xy12345.us-east-1`) */
            account: string;
            /** @description Target database */
            database: string;
            /** @description Login password */
            password: string;
            /** @description Target schema within the database */
            schema?: string;
            /** @enum {string} */
            type: "snowflake";
            /** @description Login username */
            user: string;
            /** @description Compute warehouse name */
            warehouse?: string;
        } | {
            /**
             * @description Optional path to service account credentials JSON file.
             *     Falls back to GOOGLE_APPLICATION_CREDENTIALS env var if omitted.
             */
            credentials_path?: string | null;
            /** @description BigQuery dataset name */
            dataset: string;
            /** @description GCP project ID */
            project_id: string;
            /** @enum {string} */
            type: "bigquery";
        } | {
            file_path: string;
            /** @enum {string} */
            type: "duckdb";
        } | {
            /** @enum {string} */
            type: "code_repository";
            url: string;
        };
        PromptCreateRequest: {
            content: string;
            metadata?: unknown;
            name: string;
            variables?: unknown;
            version: string;
            /**
             * Format: uuid
             * @description When set, the prompt is a workspace-scoped override of the
             *     global template. When `None`, it's a new global version.
             */
            workspace_id?: string | null;
        };
        PromptInfo: {
            name: string;
            version: string;
        };
        /**
         * @description Prompt template row (admin-only — wired by `routes/prompts_admin.rs`).
         *
         *     `version` is the semver string (e.g. `1.2.3`). `workspace_id = null`
         *     means the template is global; a concrete uuid scopes it to one
         *     workspace (used by the `/api/admin/prompts` workspace-override flow).
         */
        PromptTemplateRow: {
            content: string;
            /** Format: date-time */
            created_at: string;
            created_by: string;
            /** Format: uuid */
            id: string;
            is_active: boolean;
            metadata: unknown;
            name: string;
            variables: unknown;
            version: string;
            /** Format: uuid */
            workspace_id?: string | null;
        };
        PromptUpdateRequest: {
            content?: string | null;
            is_active?: boolean | null;
            variables?: unknown;
        };
        /** @description Query execution record. */
        QueryExecution: {
            compiled_query: string;
            compiled_target: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            execution_time_ms: number;
            explanation: string;
            /** Format: uuid */
            id: string;
            model: string;
            ontology_lineage_id: string;
            ontology_snapshot?: unknown;
            /** Format: int32 */
            ontology_version: number;
            query_bindings?: unknown;
            query_ir: unknown;
            question: string;
            results: unknown;
            /** Format: uuid */
            saved_ontology_id?: string | null;
            user_id: string;
            widget?: unknown;
        };
        /** @description Query execution summary (lightweight, for list endpoints). */
        QueryExecutionSummary: {
            compiled_target: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            execution_time_ms: number;
            has_widget: boolean;
            /** Format: uuid */
            id: string;
            model: string;
            ontology_lineage_id: string;
            /** Format: int32 */
            ontology_version: number;
            question: string;
            /** Format: int64 */
            row_count: number;
        };
        QueryRawRequest: {
            /** @description Raw query statement in the target language (e.g., Cypher). */
            query: string;
        };
        QueryRawResponse: {
            /** @description The query that was executed. */
            query: string;
            /** @description Query result rows and metadata. */
            results?: Record<string, never> | null;
            /** @description Compiler target language (e.g., "cypher"). */
            target: string;
        };
        /** @description Saved ontology — a completed, frozen ontology. */
        SavedOntology: {
            /** Format: date-time */
            created_at: string;
            created_by: string;
            description?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            ontology_ir: unknown;
            /** Format: int32 */
            version: number;
        };
        UiConfig: {
            elk_direction: string;
            elk_edge_routing: string;
            /** Format: int64 */
            elk_layer_spacing: number;
            /** Format: int64 */
            elk_node_spacing: number;
            /** Format: int64 */
            worker_timeout_ms: number;
        };
        UpdateDecisionsRequest: {
            /** @description User design decisions. */
            design_options: Record<string, never>;
            /** Format: int32 */
            revision: number;
        };
        /** @description Workbench perspective — saved canvas state. */
        WorkbenchPerspective: {
            collapsed_groups: unknown;
            /** Format: date-time */
            created_at: string;
            filters: unknown;
            /** Format: uuid */
            id: string;
            is_default: boolean;
            lineage_id: string;
            name: string;
            positions: unknown;
            /** Format: uuid */
            project_id?: string | null;
            topology_signature: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            viewport: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_prompt_templates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All prompt templates (active + inactive) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplateRow"][];
                };
            };
            /** @description Admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_prompt_template: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptCreateRequest"];
            };
        };
        responses: {
            /** @description New template version created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplateRow"];
                };
            };
            /** @description Invalid semver version */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_prompt_template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt template id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prompt template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplateRow"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_prompt_template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt template id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_prompt_template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt template id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptUpdateRequest"];
            };
        };
        responses: {
            /** @description Template updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatStreamRequest"];
            };
        };
        responses: {
            /** @description SSE stream: Agent events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration grouped by category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    update_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Config updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No updates provided */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    get_ui_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frontend-relevant configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiConfig"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    plan_load: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadPlanRequest"];
            };
        };
        responses: {
            /** @description Load plan generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadPlanResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    execute_load: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadExecuteRequest"];
            };
        };
        responses: {
            /** @description Load executed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadExecuteResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Graph database not connected */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    list_ontologies: {
        parameters: {
            query?: {
                /** @description Max items to return (default 50, max 100) */
                limit?: number;
                /** @description Opaque cursor from a previous response */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of saved ontologies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    export_ontology: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OntologyIR to export */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description OntologyInputIR exchange format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    export_cypher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OntologyIR */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Cypher DDL statements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    export_graphql: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OntologyIR */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description GraphQL schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    export_mermaid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OntologyIR */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Mermaid ER diagram */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    export_owl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OntologyIR */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description OWL/Turtle ontology */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    export_python: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OntologyIR */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Python dataclass definitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    export_shacl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OntologyIR */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description SHACL shapes in Turtle format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    export_typescript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OntologyIR */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description TypeScript interface definitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    import_owl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OntologyImportRequest"];
            };
        };
        responses: {
            /** @description Parsed OntologyIR */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Parse or validation errors */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    normalize_ontology: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OntologyInputIR to normalize */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Normalized OntologyIR */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation errors */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    save_perspective: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerspectiveUpsertRequest"];
            };
        };
        responses: {
            /** @description Perspective saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_perspectives: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lineage ID */
                lineage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of perspectives for this lineage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_best_perspective: {
        parameters: {
            query: {
                /** @description Topology hash for fallback matching */
                topology_signature: string;
            };
            header?: never;
            path: {
                /** @description Lineage ID */
                lineage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Best matching perspective (null if none) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_default_perspective: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lineage ID */
                lineage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default perspective (null if none set) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    delete_perspective: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Perspective ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perspective deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Perspective not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    list_pins: {
        parameters: {
            query?: {
                /** @description Max items to return (default 50, max 100) */
                limit?: number;
                /** @description Opaque cursor from a previous response */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated pin list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    create_pin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinCreateRequest"];
            };
        };
        responses: {
            /** @description Pin created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    delete_pin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pin ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pin deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query?: {
                /** @description Max items to return (default 50, max 100) */
                limit?: number;
                /** @description Opaque cursor from a previous response */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated project list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Base ontology not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    delete_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    apply_reconcile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectReconcileRequest"];
            };
        };
        responses: {
            /** @description Reconcile decisions applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRefineResponse"];
                };
            };
            /** @description Invalid decisions */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Reconciled ontology invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    complete_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCompleteRequest"];
            };
        };
        responses: {
            /** @description Project completed, ontology saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Project has no ontology */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Quality gate failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    update_decisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDecisionsRequest"];
            };
        };
        responses: {
            /** @description Decisions updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Revision conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    design_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectDesignRequest"];
            };
        };
        responses: {
            /** @description Ontology designed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDesignResponse"];
                };
            };
            /** @description Invalid input or large schema gate */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description LLM timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    design_project_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectDesignRequest"];
            };
        };
        responses: {
            /** @description SSE stream: phase* -> result events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    edit_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectEditRequest"];
            };
        };
        responses: {
            /** @description Edit commands generated and optionally applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEditResponse"];
                };
            };
            /** @description Empty request or no ontology */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Command validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description LLM timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    extend_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectExtendRequest"];
            };
        };
        responses: {
            /** @description Ontology extended with new source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectExtendResponse"];
                };
            };
            /** @description No ontology or empty source data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description LLM timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    apply_ontology_commands: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Design project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OntologyCommandsRequest"];
            };
        };
        responses: {
            /** @description Commands applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OntologyCommandsResponse"];
                };
            };
            /** @description Empty commands or invalid ontology */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Command execution or validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    reanalyze_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectReanalyzeRequest"];
            };
        };
        responses: {
            /** @description Source re-analyzed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectReanalyzeResponse"];
                };
            };
            /** @description Source type mismatch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    refine_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectRefineRequest"];
            };
        };
        responses: {
            /** @description Ontology refined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRefineResponse"];
                };
            };
            /** @description No runtime or additional context */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Uncertain reconcile matches */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description LLM timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    refine_project_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectRefineRequest"];
            };
        };
        responses: {
            /** @description SSE stream: phase* -> result/uncertain_reconcile events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description No runtime or context */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    list_revisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ontology revision snapshots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    get_revision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
                /** @description Revision number */
                rev: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ontology revision snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Revision not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    restore_revision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
                /** @description Revision number to restore */
                rev: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revision restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRestoreResponse"];
                };
            };
            /** @description Project or revision not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    list_prompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of loaded prompt templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptInfo"][];
                };
            };
        };
    };
    execute_from_ir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteFromIrRequest"];
            };
        };
        responses: {
            /** @description Compiled and executed query result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecuteFromIrResponse"];
                };
            };
            /** @description Invalid QueryIR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Compilation or execution failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Graph database not connected */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Query timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    list_executions: {
        parameters: {
            query?: {
                /** @description Max items to return (default 50, max 100) */
                limit?: number;
                /** @description Opaque cursor from a previous response */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated query execution history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_execution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Query execution ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Query execution details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Execution not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
    raw_query: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRawRequest"];
            };
        };
        responses: {
            /** @description Raw query result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryRawResponse"];
                };
            };
            /** @description Empty query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Query execution failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Graph database not connected */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
            /** @description Query timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
    };
}
