// ---------------------------------------------------------------------------
// Ontology IR — FE domain types
// ---------------------------------------------------------------------------
//
// These types are the FE's stable working shapes. They are deliberately
// declared by hand rather than auto-imported from `api.generated.ts`
// so the FE business logic isn't forced to handle every optional/empty
// edge of the wire schema (utoipa marks `Vec<T> + serde(default)` as
// optional in OpenAPI, which is technically correct but too noisy at
// every render).
//
// **What the hand-written types still guarantee:** every field type
// matches the wire format byte-for-byte. `description` is
// `LocalizedText`, not `string` — pre-fix this was the major drift
// that silently mangled translations through the glossary form.
//
// The generated `api.generated.ts` (regenerated by `pnpm gen:openapi`)
// is the source of truth for *new* code that needs to consume
// optional-array semantics directly. The OpenAPI schema-pinned test
// in `crates/ox-api/tests/openapi_schema_pinned.rs` ensures the wire
// shape stays as-declared — drift between hand-written + wire fails
// CI.

import type { components } from "./api.generated";

// LocalizedText flows verbatim from the wire spec — every IR field
// declared `LocalizedText` on the backend uses this exact shape.
export type LocalizedText = components["schemas"]["LocalizedText"];

// ---------------------------------------------------------------------------
// IR collection types — wire-shape-correct, FE-friendly defaults
// ---------------------------------------------------------------------------

export type Cardinality = "one_to_one" | "one_to_many" | "many_to_one" | "many_to_many";

export type DataClassification = "public" | "internal" | "confidential" | "restricted";

/** Cursor-based pagination wrapper. */
export interface CursorPage<T> {
  items: T[];
  next_cursor?: string;
}

export interface OntologyIR {
  id: string;
  name: string;
  description?: LocalizedText | null;
  version: number;
  node_types: NodeTypeDef[];
  edge_types: EdgeTypeDef[];
  indexes?: IndexDef[];
  glossary?: unknown[];
  code_systems?: unknown[];
  value_sets?: unknown[];
  notation_patterns?: unknown[];
  concept_maps?: unknown[];
  rules?: unknown[];
  provenance?: unknown[];
}

export interface NodeTypeDef {
  id: string;
  label: string;
  description?: LocalizedText | null;
  source_lineage?: SourceLineage | null;
  properties: PropertyDef[];
  constraints?: ConstraintDef[];
}

export interface EdgeTypeDef {
  id: string;
  label: string;
  description?: LocalizedText | null;
  source_node_id: string;
  target_node_id: string;
  properties: PropertyDef[];
  cardinality?: Cardinality;
}

/**
 * Backend `SourceLineage` — replaces the legacy `source_table: string`
 * field with the richer (source_id + table + primary_key) shape.
 */
export interface SourceLineage {
  source_id?: string | null;
  table: string;
  primary_key?: string[];
}

/** Tagged property type from backend: `{"type": "string"}`, `{"type": "list", "element": {...}}` */
export type PropertyType = { type: string; element?: PropertyType };

/** Display a PropertyType as a human-readable string, e.g. "string", "list<int>" */
export function formatPropertyType(pt: PropertyType): string {
  if (pt.type === "list" && pt.element) {
    return `list<${formatPropertyType(pt.element)}>`;
  }
  return pt.type;
}

export interface PropertyDef {
  id: string;
  name: string;
  property_type: PropertyType;
  nullable?: boolean;
  default_value?: unknown;
  description?: LocalizedText | null;
  source_column?: string | null;
  classification?: DataClassification | null;
  glossary_term_id?: string | null;
  value_set_id?: string | null;
  notation_pattern_id?: string | null;
}

export type ConstraintDef =
  | { id: string; type: "unique"; property_ids: string[] }
  | { id: string; type: "exists"; property_id: string }
  | { id: string; type: "node_key"; property_ids: string[] };

export interface IndexDef {
  id: string;
  type: string;
  node_id: string;
  property_id?: string;
  property_ids?: string[];
  name?: string;
  dimensions?: number;
  similarity?: string;
}

// ---------------------------------------------------------------------------
// QueryIR — UI-side shape (separate from wire QueryIR in lib/api)
// ---------------------------------------------------------------------------

export interface QueryIR {
  operation: QueryOp;
  limit?: number | null;
  skip?: number | null;
  order_by: OrderClause[];
}

export type QueryOp = Record<string, unknown> & {
  op: string;
};

export interface OrderClause {
  projection: Record<string, unknown>;
  direction: "asc" | "desc";
}

export interface QueryResult {
  columns: string[];
  rows: Record<string, unknown>[];
  metadata?: QueryMetadata;
}

export interface QueryMetadata {
  execution_time_ms: number;
  rows_returned: number;
  nodes_affected?: number | null;
  edges_affected?: number | null;
  provenance?: QueryProvenance;
  warnings?: QueryDiagnostic[];
  [extra: string]: unknown;
}

export type DiagnosticLevel = "error" | "warning" | "info";

export interface QueryDiagnostic {
  validator: string;
  level: DiagnosticLevel;
  message: string;
}

export interface QueryProvenance {
  ontology_id?: string;
  ontology_version?: string;
  as_of?: string;
  source_ids?: string[];
  type_ids?: string[];
  filter_summary?: string;
}

// ---------------------------------------------------------------------------
// WidgetSpec — FE rendering overlay
// ---------------------------------------------------------------------------

export type WidgetSpec = Record<string, unknown> & {
  widget_type?: string;
  title?: string;
  reason?: string;
  chart_type?: string;
  content?: string;
  x_axis?: { field?: string };
  y_axis?: { field?: string };
  data_mapping?: {
    label?: string;
    value?: string;
    delta?: string;
  };
  series?: Array<{ field?: string }>;
  columns?: Array<{ key: string; label?: string }>;
  thresholds?: {
    warning?: number;
    critical?: number;
    direction?: "above" | "below";
  };
  node_config?: NodeVizConfig;
  edge_config?: EdgeVizConfig;
  layout?: GraphLayout;
  interactive?: boolean;
  zoom_enabled?: boolean;
  max_nodes?: number;
};

export type GraphLayout = "force" | "hierarchical" | "radial" | "dagre";

export interface NodeVizConfig {
  label_field: string;
  color_field?: string;
  color_map?: ColorMapping[];
  size_field?: string;
  tooltip_fields: string[];
}

export interface EdgeVizConfig {
  label_field?: string;
  color_field?: string;
  weight_field?: string;
  directed: boolean;
}

export interface ColorMapping {
  value: string;
  color: string;
}

// ---------------------------------------------------------------------------
// OntologyCommand — incremental schema edit ops
// ---------------------------------------------------------------------------

export type OntologyCommand =
  | { op: "add_node"; id: string; label: string; description?: LocalizedText; source_table?: string }
  | { op: "delete_node"; node_id: string }
  | { op: "rename_node"; node_id: string; new_label: string }
  | { op: "update_node_description"; node_id: string; description?: LocalizedText }
  | { op: "add_edge"; id: string; label: string; source_node_id: string; target_node_id: string; cardinality: Cardinality }
  | { op: "delete_edge"; edge_id: string }
  | { op: "rename_edge"; edge_id: string; new_label: string }
  | { op: "update_edge_cardinality"; edge_id: string; cardinality: Cardinality }
  | { op: "update_edge_description"; edge_id: string; description?: LocalizedText }
  | { op: "add_property"; owner_id: string; property: PropertyDef }
  | { op: "delete_property"; owner_id: string; property_id: string }
  | { op: "update_property"; owner_id: string; property_id: string; patch: PropertyPatch }
  | { op: "add_constraint"; node_id: string; constraint: ConstraintDef }
  | { op: "remove_constraint"; node_id: string; constraint_id: string }
  | { op: "add_index"; index: IndexDef }
  | { op: "remove_index"; index_id: string }
  | { op: "batch"; description: string; commands: OntologyCommand[] };

export interface PropertyPatch {
  name?: string;
  property_type?: PropertyType;
  nullable?: boolean;
  default_value?: unknown | null;
  description?: LocalizedText | null;
  source_column?: string | null;
}

// --- Ontologies (Λ storage model) ----------------------------------------

export interface CurrentVersionSummary {
  version_id: string;
  version: string;
  committed_by: string;
  commit_message: string;
  created_at: string;
}

export interface OntologyListItem {
  id: string;
  lineage_id: string;
  name: string;
  description: LocalizedText;
  created_at: string;
  updated_at: string;
  current_version?: CurrentVersionSummary;
}

export interface OntologyDetail {
  id: string;
  lineage_id: string;
  name: string;
  description: LocalizedText;
  created_at: string;
  updated_at: string;
  current_version?: CurrentVersionSummary;
  ontology_ir?: OntologyIR;
}

export interface PromptInfo {
  name: string;
  version: string;
}

// --- Element Verification --------------------------------------------

export interface ElementVerification {
  id: string;
  ontology_lineage_id: string;
  element_id: string;
  element_kind: "node" | "edge" | "property";
  verified_by: string;
  verified_by_name?: string;
  review_notes?: string;
  invalidated_at?: string;
  invalidation_reason?: string;
  created_at: string;
}
