// ---------------------------------------------------------------------------
// Ontology IR — FE domain types
// ---------------------------------------------------------------------------
//
// These types are the FE's stable working shapes. They are deliberately
// declared by hand rather than auto-imported from `api.generated.ts`
// so the FE business logic isn't forced to handle every optional/empty
// edge of the wire schema (utoipa marks `Vec<T> + serde(default)` as
// optional in OpenAPI, which is technically correct but too noisy at
// every render).
//
// **What the hand-written types still guarantee:** every field type
// matches the wire format byte-for-byte. `description` is
// `LocalizedText`, not `string` — pre-fix this was the major drift
// that silently mangled translations through the glossary form.
//
// The generated `api.generated.ts` (regenerated by `pnpm gen:openapi`)
// is the source of truth for *new* code that needs to consume
// optional-array semantics directly. The OpenAPI schema-pinned test
// in `crates/ox-api/tests/openapi_schema_pinned.rs` ensures the wire
// shape stays as-declared — drift between hand-written + wire fails
// CI.

import type { components } from "./api.generated";

// LocalizedText flows verbatim from the wire spec — every IR field
// declared `LocalizedText` on the backend uses this exact shape.
export type LocalizedText = components["schemas"]["LocalizedText"];

// ---------------------------------------------------------------------------
// IR collection types — wire-shape-correct, FE-friendly defaults
// ---------------------------------------------------------------------------

export type Cardinality = "one_to_one" | "one_to_many" | "many_to_one" | "many_to_many";

export type DataClassification = "public" | "internal" | "confidential" | "restricted";

/** Cursor-based pagination wrapper. */
export interface CursorPage<T> {
  items: T[];
  next_cursor?: string;
}

// Optionality below tracks the *wire shape*, not loose
// over-permissiveness. The rule:
//   - `T` (required, no `?`): backend always serialises (no Option,
//     or Option without `skip_serializing_if`).
//   - `T?` (optional, no `| null`): backend `Option<T>` with
//     `skip_serializing_if = "Option::is_none"` — the field is
//     omitted from JSON when absent. The agent prompt path saves
//     the `null` token cost on every absent field.
// `T | null` is reserved for backend fields that genuinely send
// `null` (none today). A naive `?: T | null` everywhere
// under-promised the actual wire shape.

export interface OntologyIR {
  id: string;
  name: string;
  /** `LocalizedText` defaults to `{default: "", translations: {}}`,
   *  so the wire always carries the field — empty when no
   *  description is set. */
  description: LocalizedText;
  version: number;
  node_types: NodeTypeDef[];
  edge_types: EdgeTypeDef[];
  /** Backend `Vec<IndexDef>` with `skip_serializing_if =
   *  "Vec::is_empty"` — omitted when empty. */
  indexes?: IndexDef[];
  glossary?: unknown[];
  code_systems?: unknown[];
  value_sets?: unknown[];
  notation_patterns?: unknown[];
  concept_maps?: ConceptMapDef[];
  rules?: unknown[];
  provenance?: unknown[];
}

export interface NodeTypeDef {
  id: string;
  label: string;
  /** Always serialised (`LocalizedText` non-Option on backend). */
  description: LocalizedText;
  /** `Option<SourceLineage>` with skip — omitted when absent. */
  source_lineage?: SourceLineage;
  properties: PropertyDef[];
  /** `Vec<ConstraintDef>` with skip — omitted when empty. */
  constraints?: ConstraintDef[];
}

export interface EdgeTypeDef {
  id: string;
  label: string;
  /** Always serialised (`LocalizedText` non-Option on backend). */
  description: LocalizedText;
  source_node_id: string;
  target_node_id: string;
  properties: PropertyDef[];
  cardinality?: Cardinality;
  /** UML / OMG relationship classification — drives canvas markers
   *  (filled diamond for `composition`, hollow for `aggregation`).
   *  Defaults to `"association"` when omitted. */
  kind?: EdgeKind;
}

/**
 * UML-aligned edge classification. Mirrors the Rust `EdgeKind` enum.
 * Source-side marker rendering on the canvas is driven by this field.
 */
export type EdgeKind = "association" | "composition" | "aggregation";

/**
 * Backend `SourceLineage` — replaces the legacy `source_table: string`
 * field with the richer (source_id + table + primary_key) shape.
 */
export interface SourceLineage {
  /** Optional with skip — omitted when absent. */
  source_id?: string;
  table: string;
  /** `Vec<String>` with skip — omitted when empty. */
  primary_key?: string[];
}

/** Tagged property type from backend: `{"type": "string"}`, `{"type": "list", "element": {...}}` */
export type PropertyType = { type: string; element?: PropertyType };

/** Display a PropertyType as a human-readable string, e.g. "string", "list<int>" */
export function formatPropertyType(pt: PropertyType): string {
  if (pt.type === "list" && pt.element) {
    return `list<${formatPropertyType(pt.element)}>`;
  }
  return pt.type;
}

/** FHIR-style strength for a property binding. */
export type BindingStrength =
  | "required"
  | "preferred"
  | "extensible"
  | "example";

/**
 * Wire shape of `ox_ontology::PropertyBinding` — discriminated by
 * the registry kind it points at. Each variant carries only the
 * fields meaningful for that target: `strength` and
 * `concept_map_id` apply where vocabulary enforcement /
 * translation makes sense; `value_range` and `glossary` carry
 * neither (ranges classify; glossary is a semantic anchor).
 */
export type PropertyBinding =
  | {
      kind: "value_set";
      id: string;
      strength?: BindingStrength;
      concept_map_id?: string;
      valid_from?: string;
      valid_to?: string;
    }
  | {
      kind: "code_system";
      id: string;
      strength?: BindingStrength;
      concept_map_id?: string;
      valid_from?: string;
      valid_to?: string;
    }
  | {
      kind: "notation_pattern";
      id: string;
      strength?: BindingStrength;
      valid_from?: string;
      valid_to?: string;
    }
  | {
      kind: "value_range";
      id: string;
      valid_from?: string;
      valid_to?: string;
    }
  | {
      kind: "glossary";
      id: string;
      valid_from?: string;
      valid_to?: string;
    };

/**
 * Lightweight `(kind, id)` selector for a `PropertyBinding`. Used by
 * the unbind edit op and dedup keys that don't care about the
 * binding's strength / concept-map / temporal metadata.
 */
export type PropertyBindingHandle =
  | { kind: "value_set"; id: string }
  | { kind: "code_system"; id: string }
  | { kind: "notation_pattern"; id: string }
  | { kind: "value_range"; id: string }
  | { kind: "glossary"; id: string };

/** Wire shape of `ox_ontology::ConceptMapDef` — translation table
 *  between two `CodeSystem`s. The IR carries these so a property
 *  binding can declare both the bound vocabulary (`target`) and the
 *  translation map used to reach it (`concept_map_id`). */
export interface ConceptMapMapping {
  source_code: string;
  target_code: string;
  equivalence:
    | "equivalent"
    | "narrower_than_target"
    | "broader_than_target"
    | "related"
    | "not_related";
  comment?: LocalizedText;
}

export interface ConceptMapDef {
  id: string;
  name: string;
  display_name?: LocalizedText;
  description?: LocalizedText;
  version: string;
  source_system_id: string;
  target_system_id: string;
  mappings: ConceptMapMapping[];
}

export interface PropertyDef {
  id: string;
  name: string;
  property_type: PropertyType;
  nullable?: boolean;
  /** Backend `Option<PropertyValue>` with skip — omitted when absent. */
  default_value?: unknown;
  /** Always serialised (`LocalizedText` non-Option on backend). */
  description: LocalizedText;
  source_column?: string;
  classification?: DataClassification;
  /** Ordered semantic bindings (replaces the old per-target id fields). */
  bindings?: PropertyBinding[];
}

export type ConstraintDef =
  | { id: string; type: "unique"; property_ids: string[] }
  | { id: string; type: "exists"; property_id: string }
  | { id: string; type: "node_key"; property_ids: string[] };

export interface IndexDef {
  id: string;
  type: string;
  node_id: string;
  property_id?: string;
  property_ids?: string[];
  name?: string;
  dimensions?: number;
  similarity?: string;
}

// ---------------------------------------------------------------------------
// QueryIR — UI-side shape (separate from wire QueryIR in lib/api)
// ---------------------------------------------------------------------------

export interface QueryIR {
  operation: QueryOp;
  limit?: number | null;
  skip?: number | null;
  order_by: OrderClause[];
}

export type QueryOp = Record<string, unknown> & {
  op: string;
};

export interface OrderClause {
  projection: Record<string, unknown>;
  direction: "asc" | "desc";
}

export interface QueryResult {
  columns: string[];
  rows: Record<string, unknown>[];
  metadata?: QueryMetadata;
}

export interface QueryMetadata {
  execution_time_ms: number;
  rows_returned: number;
  nodes_affected?: number | null;
  edges_affected?: number | null;
  provenance?: QueryProvenance;
  warnings?: QueryDiagnostic[];
  [extra: string]: unknown;
}

export type DiagnosticLevel = "error" | "warning" | "info";

/**
 * Structured diagnostic — RFC 7807 / gRPC `google.rpc.Status` shape.
 * Mirrors Rust `ox_core::DiagnosticMessage`.
 *
 * - `code` — stable dotted identifier (`<surface>.<phase>.<kind>`),
 *   the catalogue key the FE renders translations against.
 * - `message` — English fallback rendering; goes to logs / alerts
 *   and to consumers without a catalogue entry for `code`.
 * - `params` — placeholder values for the catalogue template
 *   (ICU MessageFormat). Empty object when nothing parameterises.
 *
 * Render via `useTranslations()` `t(diag.code, diag.params)`; the
 * English `message` is the safe fallback when a catalogue key is
 * missing.
 */
export interface DiagnosticMessage {
  code: string;
  message: string;
  params?: Record<string, unknown>;
}

export interface QueryDiagnostic {
  validator: string;
  level: DiagnosticLevel;
  /** Structured diagnostic — `code` + English `message` + `params`.
   *  See {@link DiagnosticMessage}. */
  message: DiagnosticMessage;
}

/**
 * One output-column ↔ source-column attribution edge from
 * `QueryProvenance.column_lineage`. Mirrors `ox_query_ir::ColumnLineage`.
 */
export interface ColumnLineage {
  output_column: string;
  source_id: string;
  source_column: string;
  /** Optional textual transform — present when the value is not the
   *  source column verbatim (e.g. `"UPPER(col)"`, ConceptMap rewrite). */
  transform?: string;
}

export interface QueryProvenance {
  ontology_id?: string;
  ontology_version?: string;
  as_of?: string;
  source_ids?: string[];
  type_ids?: string[];
  filter_summary?: string;
  /** Per-output-column attribution. Populated only on the federation
   *  path; raw-Cypher and from-IR paths leave this empty. */
  column_lineage?: ColumnLineage[];
  /** Content-addressed registry hashes — re-run anchor for
   *  reproducibility. Keyed by `code_systems`/`glossary`/etc. */
  registry_versions?: Record<string, string>;
}

// ---------------------------------------------------------------------------
// WidgetSpec — FE rendering overlay
// ---------------------------------------------------------------------------

export type WidgetSpec = Record<string, unknown> & {
  widget_type?: string;
  title?: string;
  reason?: string;
  chart_type?: string;
  content?: string;
  x_axis?: { field?: string };
  y_axis?: { field?: string };
  data_mapping?: {
    label?: string;
    value?: string;
    delta?: string;
  };
  series?: Array<{ field?: string }>;
  columns?: Array<{ key: string; label?: string }>;
  thresholds?: {
    warning?: number;
    critical?: number;
    direction?: "above" | "below";
  };
  node_config?: NodeVizConfig;
  edge_config?: EdgeVizConfig;
  layout?: GraphLayout;
  interactive?: boolean;
  zoom_enabled?: boolean;
  max_nodes?: number;
};

export type GraphLayout = "force" | "hierarchical" | "radial" | "dagre";

export interface NodeVizConfig {
  label_field: string;
  color_field?: string;
  color_map?: ColorMapping[];
  size_field?: string;
  tooltip_fields: string[];
}

export interface EdgeVizConfig {
  label_field?: string;
  color_field?: string;
  weight_field?: string;
  directed: boolean;
}

export interface ColorMapping {
  value: string;
  color: string;
}

// ---------------------------------------------------------------------------
// OntologyCommand — incremental schema edit ops
// ---------------------------------------------------------------------------

export type OntologyCommand =
  | { op: "add_node"; id: string; label: string; description?: LocalizedText; source_table?: string }
  | { op: "delete_node"; node_id: string }
  | { op: "rename_node"; node_id: string; new_label: string }
  | { op: "update_node_description"; node_id: string; description?: LocalizedText }
  | { op: "add_edge"; id: string; label: string; source_node_id: string; target_node_id: string; cardinality: Cardinality }
  | { op: "delete_edge"; edge_id: string }
  | { op: "rename_edge"; edge_id: string; new_label: string }
  | { op: "update_edge_cardinality"; edge_id: string; cardinality: Cardinality }
  | { op: "update_edge_description"; edge_id: string; description?: LocalizedText }
  | { op: "add_property"; owner_id: string; property: PropertyDef }
  | { op: "delete_property"; owner_id: string; property_id: string }
  | { op: "update_property"; owner_id: string; property_id: string; patch: PropertyPatch }
  | { op: "add_constraint"; node_id: string; constraint: ConstraintDef }
  | { op: "remove_constraint"; node_id: string; constraint_id: string }
  | { op: "add_index"; index: IndexDef }
  | { op: "remove_index"; index_id: string }
  | { op: "batch"; description: string; commands: OntologyCommand[] };

/**
 * PATCH-style update for a property. The wire semantic *requires*
 * the absent / null distinction:
 *   - field omitted = leave unchanged.
 *   - field present with `null` = clear / unset.
 *   - field present with value = set to value.
 *
 * `?: T | null` is correct here — the only place in the IR types
 * where `null` carries meaning beyond "absent."
 */
export interface PropertyPatch {
  name?: string;
  property_type?: PropertyType;
  nullable?: boolean;
  default_value?: unknown | null;
  description?: LocalizedText | null;
  source_column?: string | null;
}

// --- Ontologies (Λ storage model) ----------------------------------------

export interface CurrentVersionSummary {
  version_id: string;
  version: string;
  committed_by: string;
  commit_message: string;
  created_at: string;
}

export interface OntologyListItem {
  id: string;
  lineage_id: string;
  name: string;
  description: LocalizedText;
  created_at: string;
  updated_at: string;
  current_version?: CurrentVersionSummary;
}

export interface OntologyDetail {
  id: string;
  lineage_id: string;
  name: string;
  description: LocalizedText;
  created_at: string;
  updated_at: string;
  current_version?: CurrentVersionSummary;
  ontology_ir?: OntologyIR;
}

export interface PromptInfo {
  name: string;
  version: string;
}

// --- Element Verification --------------------------------------------

export interface ElementVerification {
  id: string;
  ontology_lineage_id: string;
  element_id: string;
  element_kind: "node" | "edge" | "property";
  verified_by: string;
  verified_by_name?: string;
  review_notes?: string;
  invalidated_at?: string;
  invalidation_reason?: string;
  created_at: string;
}
