use ox_core::ontology_ir::OntologyIR;
use ox_core::types::PropertyType;

/// Generate Python dataclass definitions from an OntologyIR.
///
/// Produces `@dataclass` classes for each node type and edge type,
/// with property types mapped to their Python equivalents.
/// Non-nullable fields are emitted before nullable (Optional) fields
/// to satisfy Python's dataclass field ordering rules.
pub fn generate_python(ontology: &OntologyIR) -> String {
    let mut lines: Vec<String> = Vec::new();

    lines.push("# Auto-generated by Ontosyx \u{2014} do not edit manually".to_string());
    lines.push(format!(
        "# Ontology: {} v{}",
        ontology.name, ontology.version
    ));
    lines.push(String::new());

    // Collect which imports are actually needed
    let mut needs_datetime = false;
    let mut needs_date = false;
    let mut needs_optional = false;
    let mut needs_any = false;

    for node in &ontology.node_types {
        check_imports(
            &node.properties,
            &mut needs_datetime,
            &mut needs_date,
            &mut needs_optional,
            &mut needs_any,
        );
    }
    for edge in &ontology.edge_types {
        check_imports(
            &edge.properties,
            &mut needs_datetime,
            &mut needs_date,
            &mut needs_optional,
            &mut needs_any,
        );
    }

    // Emit imports
    lines.push("from __future__ import annotations".to_string());
    lines.push("from dataclasses import dataclass, field".to_string());
    if needs_datetime || needs_date {
        let mut parts = Vec::new();
        if needs_datetime {
            parts.push("datetime");
        }
        if needs_date {
            parts.push("date");
        }
        lines.push(format!("from datetime import {}", parts.join(", ")));
    }
    let mut typing_parts = Vec::new();
    if needs_optional {
        typing_parts.push("Optional");
    }
    if needs_any {
        typing_parts.push("Any");
    }
    if !typing_parts.is_empty() {
        lines.push(format!("from typing import {}", typing_parts.join(", ")));
    }
    lines.push(String::new());
    lines.push(String::new());

    // --- Node type dataclasses ---
    for node in &ontology.node_types {
        lines.push("@dataclass".to_string());
        lines.push(format!("class {}:", py_class_name(&node.label)));

        let default_desc = format!("{} node type", node.label);
        let docstring = node.description.as_deref().unwrap_or(&default_desc);
        lines.push(format!("    \"\"\"{}\"\"\"", docstring));

        emit_properties(&mut lines, &node.properties);
        lines.push(String::new());
        lines.push(String::new());
    }

    // --- Edge type dataclasses ---
    for edge in &ontology.edge_types {
        let source_label = ontology
            .node_by_id(&edge.source_node_id)
            .map(|n| n.label.as_str())
            .unwrap_or("Unknown");
        let target_label = ontology
            .node_by_id(&edge.target_node_id)
            .map(|n| n.label.as_str())
            .unwrap_or("Unknown");

        lines.push("@dataclass".to_string());
        let class_name = format!("{}Edge", py_class_name(&edge.label));
        lines.push(format!("class {class_name}:"));
        lines.push(format!(
            "    \"\"\"Edge: {} -> {}\"\"\"",
            source_label, target_label
        ));

        // source_id and target_id are always required, placed first
        lines.push("    source_id: str".to_string());
        lines.push("    target_id: str".to_string());

        emit_properties(&mut lines, &edge.properties);
        lines.push(String::new());
        lines.push(String::new());
    }

    // Remove trailing empty lines
    while lines.last().map_or(false, |l| l.is_empty()) {
        lines.pop();
    }
    lines.push(String::new()); // single trailing newline

    lines.join("\n")
}

fn emit_properties(lines: &mut Vec<String>, properties: &[ox_core::ontology_ir::PropertyDef]) {
    // Required fields first, then optional fields (Python dataclass ordering)
    let required: Vec<_> = properties.iter().filter(|p| !p.nullable).collect();
    let optional: Vec<_> = properties.iter().filter(|p| p.nullable).collect();

    for prop in &required {
        let py_t = py_type(&prop.property_type);
        lines.push(format!("    {}: {}", py_field_name(&prop.name), py_t));
    }

    for prop in &optional {
        let py_t = py_type(&prop.property_type);
        lines.push(format!(
            "    {}: Optional[{}] = None",
            py_field_name(&prop.name),
            py_t
        ));
    }
}

fn check_imports(
    properties: &[ox_core::ontology_ir::PropertyDef],
    needs_datetime: &mut bool,
    needs_date: &mut bool,
    needs_optional: &mut bool,
    needs_any: &mut bool,
) {
    for prop in properties {
        check_type_imports(
            &prop.property_type,
            needs_datetime,
            needs_date,
            needs_optional,
            needs_any,
        );
        if prop.nullable {
            *needs_optional = true;
        }
    }
}

fn check_type_imports(
    pt: &PropertyType,
    needs_datetime: &mut bool,
    needs_date: &mut bool,
    needs_optional: &mut bool,
    needs_any: &mut bool,
) {
    match pt {
        PropertyType::DateTime => *needs_datetime = true,
        PropertyType::Date => *needs_date = true,
        PropertyType::Map => *needs_any = true,
        PropertyType::List { element } => {
            check_type_imports(element, needs_datetime, needs_date, needs_optional, needs_any);
        }
        _ => {}
    }
}

fn py_type(pt: &PropertyType) -> String {
    match pt {
        PropertyType::Bool => "bool".to_string(),
        PropertyType::Int => "int".to_string(),
        PropertyType::Float => "float".to_string(),
        PropertyType::String | PropertyType::Duration => "str".to_string(),
        PropertyType::Date => "date".to_string(),
        PropertyType::DateTime => "datetime".to_string(),
        PropertyType::Bytes => "bytes".to_string(),
        PropertyType::List { element } => format!("list[{}]", py_type(element)),
        PropertyType::Map => "dict[str, Any]".to_string(),
    }
}

fn py_class_name(name: &str) -> String {
    // Convert to PascalCase: split on _ / space / -, capitalize first letter of each segment
    // Also handles SCREAMING_SNAKE_CASE by lowercasing segments first
    let mut result = String::new();
    for segment in name.split(|c: char| c == '_' || c == ' ' || c == '-') {
        if segment.is_empty() {
            continue;
        }
        let mut chars = segment.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            let rest: String = chars.collect();
            if rest.chars().all(|c| c.is_ascii_uppercase() || !c.is_alphabetic()) {
                result.push_str(&rest.to_ascii_lowercase());
            } else {
                result.push_str(&rest);
            }
        }
    }
    if result.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        result.insert(0, '_');
    }
    result
}

fn py_field_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use ox_core::ontology_ir::{
        EdgeTypeDef, EdgeTypeId, NodeTypeDef, NodeTypeId, PropertyDef, PropertyId,
    };

    fn test_ontology() -> OntologyIR {
        OntologyIR::new(
            "test-id".to_string(),
            "TestOntology".to_string(),
            Some("A test ontology".to_string()),
            1,
            vec![
                NodeTypeDef {
                    id: NodeTypeId::new("n1"),
                    label: "Customer".to_string(),
                    description: Some("A customer".to_string()),
                    source_table: None,
                    properties: vec![
                        PropertyDef {
                            id: PropertyId::new("p1"),
                            name: "id".to_string(),
                            property_type: PropertyType::String,
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                        PropertyDef {
                            id: PropertyId::new("p2"),
                            name: "email".to_string(),
                            property_type: PropertyType::String,
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                        PropertyDef {
                            id: PropertyId::new("p3"),
                            name: "phone".to_string(),
                            property_type: PropertyType::String,
                            nullable: true,
                            default_value: None,
                            description: None,
                        },
                        PropertyDef {
                            id: PropertyId::new("p4"),
                            name: "created_at".to_string(),
                            property_type: PropertyType::DateTime,
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                    ],
                    constraints: vec![],
                },
                NodeTypeDef {
                    id: NodeTypeId::new("n2"),
                    label: "Product".to_string(),
                    description: None,
                    source_table: None,
                    properties: vec![
                        PropertyDef {
                            id: PropertyId::new("p5"),
                            name: "id".to_string(),
                            property_type: PropertyType::String,
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                        PropertyDef {
                            id: PropertyId::new("p6"),
                            name: "price".to_string(),
                            property_type: PropertyType::Float,
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                        PropertyDef {
                            id: PropertyId::new("p7"),
                            name: "tags".to_string(),
                            property_type: PropertyType::List {
                                element: Box::new(PropertyType::String),
                            },
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                    ],
                    constraints: vec![],
                },
            ],
            vec![EdgeTypeDef {
                id: EdgeTypeId::new("e1"),
                label: "PURCHASED".to_string(),
                description: Some("Customer bought a product".to_string()),
                source_node_id: NodeTypeId::new("n1"),
                target_node_id: NodeTypeId::new("n2"),
                properties: vec![PropertyDef {
                    id: PropertyId::new("ep1"),
                    name: "quantity".to_string(),
                    property_type: PropertyType::Int,
                    nullable: false,
                    default_value: None,
                    description: None,
                }],
                cardinality: ox_core::ontology_ir::Cardinality::ManyToMany,
            }],
            vec![],
        )
    }

    #[test]
    fn test_generate_python_node_dataclasses() {
        let ontology = test_ontology();
        let output = generate_python(&ontology);

        assert!(output.contains("@dataclass\nclass Customer:"));
        assert!(output.contains("    id: str"));
        assert!(output.contains("    email: str"));
        assert!(output.contains("    created_at: datetime"));
        assert!(output.contains("    phone: Optional[str] = None"));
    }

    #[test]
    fn test_generate_python_edge_dataclasses() {
        let ontology = test_ontology();
        let output = generate_python(&ontology);

        assert!(output.contains("class PurchasedEdge:"));
        assert!(output.contains("    \"\"\"Edge: Customer -> Product\"\"\""));
        assert!(output.contains("    source_id: str"));
        assert!(output.contains("    target_id: str"));
        assert!(output.contains("    quantity: int"));
    }

    #[test]
    fn test_generate_python_header_and_imports() {
        let ontology = test_ontology();
        let output = generate_python(&ontology);

        assert!(output.contains("# Auto-generated by Ontosyx"));
        assert!(output.contains("# Ontology: TestOntology v1"));
        assert!(output.contains("from __future__ import annotations"));
        assert!(output.contains("from dataclasses import dataclass, field"));
        assert!(output.contains("from datetime import datetime"));
        assert!(output.contains("from typing import Optional"));
    }

    #[test]
    fn test_required_before_optional_fields() {
        let ontology = test_ontology();
        let output = generate_python(&ontology);

        // In the Customer class, required fields (id, email, created_at)
        // should appear before optional fields (phone)
        let customer_section = output
            .split("class Customer:")
            .nth(1)
            .unwrap()
            .split("\n\n")
            .next()
            .unwrap();

        let id_pos = customer_section.find("    id: str").unwrap();
        let phone_pos = customer_section.find("    phone: Optional[str]").unwrap();
        assert!(
            id_pos < phone_pos,
            "Required field 'id' should appear before optional field 'phone'"
        );
    }
}
