use ox_core::ontology_ir::{EdgeTypeDef, NodeTypeDef, OntologyIR, PropertyDef};
use ox_core::types::PropertyType;

/// Generate TypeScript type definitions from an OntologyIR.
///
/// Produces interface declarations for each node type and edge type,
/// with property types mapped to their TypeScript equivalents.
///
/// Phase A semantic fields surface in JSDoc:
/// - `deprecated_at` → `@deprecated [reason]` in the entity / field doc.
/// - `replaced_by_id` is resolved against the ontology so the reason
///   names the successor inline.
pub fn generate_typescript(ontology: &OntologyIR) -> String {
    let mut lines: Vec<String> = Vec::new();

    lines.push("// Auto-generated by Ontosyx \u{2014} do not edit manually".to_string());
    lines.push(format!(
        "// Ontology: {} v{}",
        ontology.name, ontology.version.number
    ));
    lines.push(String::new());

    // --- Node type interfaces ---
    for node in ontology.node_types() {
        push_doc_block(
            &mut lines,
            "",
            node.description.present(),
            node_deprecation_reason(node, ontology).as_deref(),
        );
        lines.push(format!("export interface {} {{", ts_safe_name(&node.label)));

        for prop in &node.properties {
            push_property_field(&mut lines, prop, ontology);
        }

        lines.push("}".to_string());
        lines.push(String::new());
    }

    // --- Edge type interfaces ---
    for edge in ontology.edge_types() {
        let source_label = ontology
            .node_by_id(&edge.source_node_id)
            .map(|n| n.label.as_str())
            .unwrap_or("Unknown");
        let target_label = ontology
            .node_by_id(&edge.target_node_id)
            .map(|n| n.label.as_str())
            .unwrap_or("Unknown");

        let edge_summary = format!(
            "Edge: {source_label} -[{edge_label}]-> {target_label}",
            edge_label = edge.label
        );
        push_doc_block(
            &mut lines,
            "",
            Some(edge_summary.as_str()),
            edge_deprecation_reason(edge, ontology).as_deref(),
        );
        let iface_name = format!("{}Edge", ts_safe_name(&edge.label));
        lines.push(format!("export interface {iface_name} {{"));
        lines.push("  source_id: string;".to_string());
        lines.push("  target_id: string;".to_string());

        for prop in &edge.properties {
            push_property_field(&mut lines, prop, ontology);
        }

        lines.push("}".to_string());
        lines.push(String::new());
    }

    lines.join("\n")
}

/// Emit a JSDoc block prefixed with `indent` (e.g. "  " for fields). Skips
/// the block entirely when there is no description and no deprecation.
fn push_doc_block(
    lines: &mut Vec<String>,
    indent: &str,
    description: Option<&str>,
    deprecation_reason: Option<&str>,
) {
    match (description, deprecation_reason) {
        (None, None) => {}
        (Some(d), None) => lines.push(format!("{indent}/** {d} */")),
        (None, Some(r)) => lines.push(format!("{indent}/** @deprecated {r} */")),
        (Some(d), Some(r)) => {
            lines.push(format!("{indent}/**"));
            lines.push(format!("{indent} * {d}"));
            lines.push(format!("{indent} * @deprecated {r}"));
            lines.push(format!("{indent} */"));
        }
    }
}

/// Render a property as one or more TS lines (optional JSDoc + the field).
fn push_property_field(lines: &mut Vec<String>, prop: &PropertyDef, ontology: &OntologyIR) {
    let dep_reason = property_deprecation_reason(prop, ontology);
    push_doc_block(
        lines,
        "  ",
        prop.description.present(),
        dep_reason.as_deref(),
    );

    let ts_type_str = ts_type(&prop.property_type);
    let inline_hint = ts_type_comment(&prop.property_type);
    let trailing_hint = if inline_hint.is_empty() {
        String::new()
    } else {
        format!("  // {inline_hint}")
    };

    let optionality = if prop.nullable { "?" } else { "" };
    lines.push(format!(
        "  {name}{optionality}: {ts_type_str};{trailing_hint}",
        name = ts_field_name(&prop.name),
    ));
}

/// Resolve a property's deprecation reason against the ontology. Returns
/// `Some` only when the property is deprecated.
fn property_deprecation_reason(prop: &PropertyDef, ontology: &OntologyIR) -> Option<String> {
    prop.deprecated_at?;
    let reason = match &prop.replaced_by_id {
        Some(id) => match ontology.property_by_id(id.as_ref()) {
            Some((_, replacement)) => format!("Replaced by `{}`", replacement.name),
            None => "Deprecated".into(),
        },
        None => "Deprecated".into(),
    };
    Some(reason)
}

/// Resolve an edge's deprecation reason against the ontology.
fn edge_deprecation_reason(edge: &EdgeTypeDef, ontology: &OntologyIR) -> Option<String> {
    edge.deprecated_at?;
    let reason = match &edge.replaced_by_id {
        Some(id) => match ontology.edge_by_id(id.as_ref()) {
            Some(replacement) => format!("Replaced by `{}`", replacement.label),
            None => "Deprecated".into(),
        },
        None => "Deprecated".into(),
    };
    Some(reason)
}

/// Resolve a node's deprecation reason against the ontology.
fn node_deprecation_reason(node: &NodeTypeDef, ontology: &OntologyIR) -> Option<String> {
    node.deprecated_at?;
    let reason = match &node.replaced_by_id {
        Some(id) => match ontology.node_by_id(id.as_ref()) {
            Some(replacement) => format!("Replaced by `{}`", replacement.label),
            None => "Deprecated".into(),
        },
        None => "Deprecated".into(),
    };
    Some(reason)
}

fn ts_type(pt: &PropertyType) -> String {
    match pt {
        PropertyType::Bool => "boolean".to_string(),
        PropertyType::Int | PropertyType::Float => "number".to_string(),
        PropertyType::String
        | PropertyType::Date
        | PropertyType::DateTime
        | PropertyType::Duration => "string".to_string(),
        PropertyType::Bytes => "Uint8Array".to_string(),
        PropertyType::List { element } => format!("{}[]", ts_type(element)),
        PropertyType::Map => "Record<string, unknown>".to_string(),
    }
}

/// Return a comment hint for types that lose precision in TypeScript.
fn ts_type_comment(pt: &PropertyType) -> &'static str {
    match pt {
        PropertyType::Date => "ISO date",
        PropertyType::DateTime => "ISO datetime",
        PropertyType::Duration => "ISO duration",
        _ => "",
    }
}

fn ts_safe_name(name: &str) -> String {
    // Convert to PascalCase: split on _ / space / -, capitalize first letter of each segment
    // Also handles SCREAMING_SNAKE_CASE by lowercasing segments first
    let mut result = String::new();
    for segment in name.split(['_', ' ', '-']) {
        if segment.is_empty() {
            continue;
        }
        let mut chars = segment.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            // If entire segment is uppercase (like "PURCHASED"), lowercase the rest
            let rest: String = chars.collect();
            if rest
                .chars()
                .all(|c| c.is_ascii_uppercase() || !c.is_alphabetic())
            {
                result.push_str(&rest.to_ascii_lowercase());
            } else {
                result.push_str(&rest);
            }
        }
    }
    // Ensure starts with a letter
    if result.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        result.insert(0, '_');
    }
    result
}

fn ts_field_name(name: &str) -> String {
    let sanitized: String = name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    // If the name contains characters that need quoting, we'd quote it,
    // but snake_case names are already valid JS identifiers.
    sanitized
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use ox_core::LocalizedText;
    use ox_core::ontology_ir::{
        EdgeTypeDef, EdgeTypeId, NodeTypeDef, NodeTypeId, PropertyDef, PropertyId,
    };

    fn test_ontology() -> OntologyIR {
        OntologyIR::new(
            "test-id".to_string(),
            "TestOntology".to_string(),
            LocalizedText::new("A test ontology"),
            1,
            vec![
                NodeTypeDef {
                    id: NodeTypeId::new("n1"),
                    label: "Customer".to_string(),
                    description: LocalizedText::new("A customer"),
                    properties: vec![
                        PropertyDef {
                            id: PropertyId::new("p1"),
                            name: "id".to_string(),
                            property_type: PropertyType::String,
                            nullable: false,
                            default_value: None,
                            description: LocalizedText::default(),
                            classification: None,
                            ..Default::default()
                        },
                        PropertyDef {
                            id: PropertyId::new("p2"),
                            name: "email".to_string(),
                            property_type: PropertyType::String,
                            nullable: false,
                            default_value: None,
                            description: LocalizedText::default(),
                            classification: None,
                            ..Default::default()
                        },
                        PropertyDef {
                            id: PropertyId::new("p3"),
                            name: "phone".to_string(),
                            property_type: PropertyType::String,
                            nullable: true,
                            default_value: None,
                            description: LocalizedText::default(),
                            classification: None,
                            ..Default::default()
                        },
                        PropertyDef {
                            id: PropertyId::new("p4"),
                            name: "created_at".to_string(),
                            property_type: PropertyType::DateTime,
                            nullable: false,
                            default_value: None,
                            description: LocalizedText::default(),
                            classification: None,
                            ..Default::default()
                        },
                    ],
                    constraints: vec![],
                    ..Default::default()
                },
                NodeTypeDef {
                    id: NodeTypeId::new("n2"),
                    label: "Product".to_string(),
                    description: LocalizedText::default(),
                    properties: vec![
                        PropertyDef {
                            id: PropertyId::new("p5"),
                            name: "id".to_string(),
                            property_type: PropertyType::String,
                            nullable: false,
                            default_value: None,
                            description: LocalizedText::default(),
                            classification: None,
                            ..Default::default()
                        },
                        PropertyDef {
                            id: PropertyId::new("p6"),
                            name: "price".to_string(),
                            property_type: PropertyType::Float,
                            nullable: false,
                            default_value: None,
                            description: LocalizedText::default(),
                            classification: None,
                            ..Default::default()
                        },
                        PropertyDef {
                            id: PropertyId::new("p7"),
                            name: "tags".to_string(),
                            property_type: PropertyType::List {
                                element: Box::new(PropertyType::String),
                            },
                            nullable: false,
                            default_value: None,
                            description: LocalizedText::default(),
                            classification: None,
                            ..Default::default()
                        },
                    ],
                    constraints: vec![],
                    ..Default::default()
                },
            ],
            vec![EdgeTypeDef {
                id: EdgeTypeId::new("e1"),
                label: "PURCHASED".to_string(),
                description: LocalizedText::new("Customer bought a product"),
                source_node_id: NodeTypeId::new("n1"),
                target_node_id: NodeTypeId::new("n2"),
                properties: vec![PropertyDef {
                    id: PropertyId::new("ep1"),
                    name: "quantity".to_string(),
                    property_type: PropertyType::Int,
                    nullable: false,
                    default_value: None,
                    description: LocalizedText::default(),
                    classification: None,
                    ..Default::default()
                }],
                cardinality: ox_core::ontology_ir::Cardinality::ManyToMany,
                ..Default::default()
            }],
            vec![],
        )
    }

    #[test]
    fn test_generate_typescript_node_interfaces() {
        let ontology = test_ontology();
        let output = generate_typescript(&ontology);

        assert!(output.contains("export interface Customer {"));
        assert!(output.contains("  id: string;"));
        assert!(output.contains("  email: string;"));
        assert!(output.contains("  phone?: string;"));
        assert!(output.contains("  created_at: string;"));
        assert!(output.contains("export interface Product {"));
        assert!(output.contains("  price: number;"));
        assert!(output.contains("  tags: string[];"));
    }

    #[test]
    fn test_generate_typescript_edge_interfaces() {
        let ontology = test_ontology();
        let output = generate_typescript(&ontology);

        assert!(output.contains("/** Edge: Customer -[PURCHASED]-> Product */"));
        assert!(output.contains("export interface PurchasedEdge {"));
        assert!(output.contains("  source_id: string;"));
        assert!(output.contains("  target_id: string;"));
        assert!(output.contains("  quantity: number;"));
    }

    #[test]
    fn test_generate_typescript_header() {
        let ontology = test_ontology();
        let output = generate_typescript(&ontology);

        assert!(output.contains("// Auto-generated by Ontosyx"));
        assert!(output.contains("// Ontology: TestOntology v1"));
    }

    #[test]
    fn deprecated_property_emits_jsdoc_with_replacement() {
        let mut ontology = test_ontology();
        // Mark Customer.email as deprecated, replaced by `id`.
        ontology
            .update_node_type(&NodeTypeId::new("n1"), |n| {
                n.properties[1].deprecated_at = Some(chrono::Utc::now());
                n.properties[1].replaced_by_id = Some(PropertyId::new("p1"));
            })
            .unwrap();
        let output = generate_typescript(&ontology);
        assert!(
            output.contains("@deprecated Replaced by `id`"),
            "expected JSDoc @deprecated with successor name: {output}"
        );
    }

    #[test]
    fn deprecated_node_emits_jsdoc_block_above_interface() {
        let mut ontology = test_ontology();
        ontology
            .update_node_type(&NodeTypeId::new("n1"), |n| {
                n.deprecated_at = Some(chrono::Utc::now());
                n.replaced_by_id = Some(NodeTypeId::new("n2"));
            })
            .unwrap();
        let output = generate_typescript(&ontology);
        // The doc block must precede the `export interface Customer` line.
        let interface_idx = output.find("export interface Customer {").unwrap();
        let doc_block_idx = output.find("@deprecated Replaced by `Product`").unwrap();
        assert!(
            doc_block_idx < interface_idx,
            "JSDoc @deprecated must appear above the interface: {output}"
        );
    }

    #[test]
    fn deprecated_edge_emits_jsdoc_block_above_interface() {
        let mut ontology = test_ontology();
        ontology
            .update_edge_type(&EdgeTypeId::new("e1"), |e| {
                e.deprecated_at = Some(chrono::Utc::now());
            })
            .unwrap();
        let output = generate_typescript(&ontology);
        let interface_idx = output.find("export interface PurchasedEdge {").unwrap();
        let dep_idx = output.find("@deprecated Deprecated").unwrap();
        assert!(
            dep_idx < interface_idx,
            "JSDoc @deprecated must appear above the edge interface: {output}"
        );
    }
}
