use ox_core::ontology_ir::OntologyIR;
use ox_core::types::PropertyType;

/// Generate TypeScript type definitions from an OntologyIR.
///
/// Produces interface declarations for each node type and edge type,
/// with property types mapped to their TypeScript equivalents.
pub fn generate_typescript(ontology: &OntologyIR) -> String {
    let mut lines: Vec<String> = Vec::new();

    lines.push("// Auto-generated by Ontosyx \u{2014} do not edit manually".to_string());
    lines.push(format!(
        "// Ontology: {} v{}",
        ontology.name, ontology.version
    ));
    lines.push(String::new());

    // --- Node type interfaces ---
    for node in &ontology.node_types {
        if let Some(desc) = &node.description {
            lines.push(format!("/** {} */", desc));
        }
        lines.push(format!("export interface {} {{", ts_safe_name(&node.label)));

        for prop in &node.properties {
            let ts_type = ts_type(&prop.property_type);
            let comment = ts_type_comment(&prop.property_type);
            let desc_comment = prop
                .description
                .as_ref()
                .map(|d| format!("  // {d}"))
                .unwrap_or_default();
            let full_comment = if !comment.is_empty() && !desc_comment.is_empty() {
                format!("  // {comment} \u{2014} {}", desc_comment.trim_start_matches("  // "))
            } else if !comment.is_empty() {
                format!("  // {comment}")
            } else {
                desc_comment
            };

            if prop.nullable {
                lines.push(format!("  {}?: {};{}", ts_field_name(&prop.name), ts_type, full_comment));
            } else {
                lines.push(format!("  {}: {};{}", ts_field_name(&prop.name), ts_type, full_comment));
            }
        }

        lines.push("}".to_string());
        lines.push(String::new());
    }

    // --- Edge type interfaces ---
    for edge in &ontology.edge_types {
        let source_label = ontology
            .node_by_id(&edge.source_node_id)
            .map(|n| n.label.as_str())
            .unwrap_or("Unknown");
        let target_label = ontology
            .node_by_id(&edge.target_node_id)
            .map(|n| n.label.as_str())
            .unwrap_or("Unknown");

        lines.push(format!(
            "/** Edge: {} -[{}]-> {} */",
            source_label, edge.label, target_label
        ));
        let iface_name = format!("{}Edge", ts_safe_name(&edge.label));
        lines.push(format!("export interface {iface_name} {{"));
        lines.push("  source_id: string;".to_string());
        lines.push("  target_id: string;".to_string());

        for prop in &edge.properties {
            let ts_type = ts_type(&prop.property_type);
            let comment = ts_type_comment(&prop.property_type);
            let desc_comment = prop
                .description
                .as_ref()
                .map(|d| format!("  // {d}"))
                .unwrap_or_default();
            let full_comment = if !comment.is_empty() && !desc_comment.is_empty() {
                format!("  // {comment} \u{2014} {}", desc_comment.trim_start_matches("  // "))
            } else if !comment.is_empty() {
                format!("  // {comment}")
            } else {
                desc_comment
            };

            if prop.nullable {
                lines.push(format!("  {}?: {};{}", ts_field_name(&prop.name), ts_type, full_comment));
            } else {
                lines.push(format!("  {}: {};{}", ts_field_name(&prop.name), ts_type, full_comment));
            }
        }

        lines.push("}".to_string());
        lines.push(String::new());
    }

    lines.join("\n")
}

fn ts_type(pt: &PropertyType) -> String {
    match pt {
        PropertyType::Bool => "boolean".to_string(),
        PropertyType::Int | PropertyType::Float => "number".to_string(),
        PropertyType::String | PropertyType::Date | PropertyType::DateTime | PropertyType::Duration => {
            "string".to_string()
        }
        PropertyType::Bytes => "Uint8Array".to_string(),
        PropertyType::List { element } => format!("{}[]", ts_type(element)),
        PropertyType::Map => "Record<string, unknown>".to_string(),
    }
}

/// Return a comment hint for types that lose precision in TypeScript.
fn ts_type_comment(pt: &PropertyType) -> &'static str {
    match pt {
        PropertyType::Date => "ISO date",
        PropertyType::DateTime => "ISO datetime",
        PropertyType::Duration => "ISO duration",
        _ => "",
    }
}

fn ts_safe_name(name: &str) -> String {
    // Convert to PascalCase: split on _ / space / -, capitalize first letter of each segment
    // Also handles SCREAMING_SNAKE_CASE by lowercasing segments first
    let mut result = String::new();
    for segment in name.split(|c: char| c == '_' || c == ' ' || c == '-') {
        if segment.is_empty() {
            continue;
        }
        let mut chars = segment.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            // If entire segment is uppercase (like "PURCHASED"), lowercase the rest
            let rest: String = chars.collect();
            if rest.chars().all(|c| c.is_ascii_uppercase() || !c.is_alphabetic()) {
                result.push_str(&rest.to_ascii_lowercase());
            } else {
                result.push_str(&rest);
            }
        }
    }
    // Ensure starts with a letter
    if result.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        result.insert(0, '_');
    }
    result
}

fn ts_field_name(name: &str) -> String {
    let sanitized: String = name
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    // If the name contains characters that need quoting, we'd quote it,
    // but snake_case names are already valid JS identifiers.
    sanitized
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use ox_core::ontology_ir::{
        EdgeTypeDef, EdgeTypeId, NodeTypeDef, NodeTypeId, PropertyDef, PropertyId,
    };

    fn test_ontology() -> OntologyIR {
        OntologyIR::new(
            "test-id".to_string(),
            "TestOntology".to_string(),
            Some("A test ontology".to_string()),
            1,
            vec![
                NodeTypeDef {
                    id: NodeTypeId::new("n1"),
                    label: "Customer".to_string(),
                    description: Some("A customer".to_string()),
                    source_table: None,
                    properties: vec![
                        PropertyDef {
                            id: PropertyId::new("p1"),
                            name: "id".to_string(),
                            property_type: PropertyType::String,
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                        PropertyDef {
                            id: PropertyId::new("p2"),
                            name: "email".to_string(),
                            property_type: PropertyType::String,
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                        PropertyDef {
                            id: PropertyId::new("p3"),
                            name: "phone".to_string(),
                            property_type: PropertyType::String,
                            nullable: true,
                            default_value: None,
                            description: None,
                        },
                        PropertyDef {
                            id: PropertyId::new("p4"),
                            name: "created_at".to_string(),
                            property_type: PropertyType::DateTime,
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                    ],
                    constraints: vec![],
                },
                NodeTypeDef {
                    id: NodeTypeId::new("n2"),
                    label: "Product".to_string(),
                    description: None,
                    source_table: None,
                    properties: vec![
                        PropertyDef {
                            id: PropertyId::new("p5"),
                            name: "id".to_string(),
                            property_type: PropertyType::String,
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                        PropertyDef {
                            id: PropertyId::new("p6"),
                            name: "price".to_string(),
                            property_type: PropertyType::Float,
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                        PropertyDef {
                            id: PropertyId::new("p7"),
                            name: "tags".to_string(),
                            property_type: PropertyType::List {
                                element: Box::new(PropertyType::String),
                            },
                            nullable: false,
                            default_value: None,
                            description: None,
                        },
                    ],
                    constraints: vec![],
                },
            ],
            vec![EdgeTypeDef {
                id: EdgeTypeId::new("e1"),
                label: "PURCHASED".to_string(),
                description: Some("Customer bought a product".to_string()),
                source_node_id: NodeTypeId::new("n1"),
                target_node_id: NodeTypeId::new("n2"),
                properties: vec![PropertyDef {
                    id: PropertyId::new("ep1"),
                    name: "quantity".to_string(),
                    property_type: PropertyType::Int,
                    nullable: false,
                    default_value: None,
                    description: None,
                }],
                cardinality: ox_core::ontology_ir::Cardinality::ManyToMany,
            }],
            vec![],
        )
    }

    #[test]
    fn test_generate_typescript_node_interfaces() {
        let ontology = test_ontology();
        let output = generate_typescript(&ontology);

        assert!(output.contains("export interface Customer {"));
        assert!(output.contains("  id: string;"));
        assert!(output.contains("  email: string;"));
        assert!(output.contains("  phone?: string;"));
        assert!(output.contains("  created_at: string;"));
        assert!(output.contains("export interface Product {"));
        assert!(output.contains("  price: number;"));
        assert!(output.contains("  tags: string[];"));
    }

    #[test]
    fn test_generate_typescript_edge_interfaces() {
        let ontology = test_ontology();
        let output = generate_typescript(&ontology);

        assert!(output.contains("/** Edge: Customer -[PURCHASED]-> Product */"));
        assert!(output.contains("export interface PurchasedEdge {"));
        assert!(output.contains("  source_id: string;"));
        assert!(output.contains("  target_id: string;"));
        assert!(output.contains("  quantity: number;"));
    }

    #[test]
    fn test_generate_typescript_header() {
        let ontology = test_ontology();
        let output = generate_typescript(&ontology);

        assert!(output.contains("// Auto-generated by Ontosyx"));
        assert!(output.contains("// Ontology: TestOntology v1"));
    }
}
