//! Type-safe entity ID newtypes.
//!
//! The [`define_id_newtype!`] macro generates a string-backed newtype
//! wrapper with a consistent trait surface so the platform can
//! distinguish node-type ids from edge-type ids from mapping ids at
//! the type level — without writing 50 lines of boilerplate per id.
//!
//! Every id generated by this macro is:
//!
//! - a tuple struct `pub struct Name(pub String)` — the wire format
//!   is still a bare string (`#[serde(transparent)]`), so migrating
//!   an existing field from `String` to a typed id is a type-only
//!   change on the Rust side.
//! - constructible via `Name::new(s)`, `Name::from(&str)`,
//!   `Name::from(String)`.
//! - comparable against `str` / `&str` / `String` on both sides.
//! - dereferenceable to `&str` — so `id.starts_with("prefix")` and
//!   `HashMap<Name, T>` lookups by `&str` work without copies.
//! - `Display`able as its wrapped string.
//!
//! The macro is deliberately **unvalidated**. Validation lives on
//! dedicated newtypes like [`crate::graph_label::GraphLabel`] and
//! [`crate::property_key::PropertyKey`]. Ids are opaque identifiers —
//! the platform does not care what characters are in them, only
//! that a `NodeTypeId` never gets mixed up with an `EdgeTypeId`.
//!
//! # Example
//!
//! ```ignore
//! ox_core::define_id_newtype!(
//!     /// Stable identifier for a mapping definition.
//!     MappingId
//! );
//! ```
//!
//! `MappingId` is now defined with every trait the rest of the
//! platform expects.

/// Declare a string-backed, type-safe identifier newtype. See the
/// module-level documentation for the trait surface and design notes.
#[macro_export]
macro_rules! define_id_newtype {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(
            Debug,
            Clone,
            Default,
            PartialEq,
            Eq,
            Hash,
            ::serde::Serialize,
            ::serde::Deserialize,
            ::schemars::JsonSchema,
        )]
        #[serde(transparent)]
        pub struct $name(pub ::std::string::String);

        impl $name {
            /// Wrap a string-like value as this id type.
            pub fn new(s: impl Into<::std::string::String>) -> Self {
                Self(s.into())
            }

            /// Borrow the underlying string.
            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl ::std::ops::Deref for $name {
            type Target = str;
            fn deref(&self) -> &str {
                &self.0
            }
        }

        impl ::std::convert::AsRef<str> for $name {
            fn as_ref(&self) -> &str {
                &self.0
            }
        }

        impl ::std::convert::From<::std::string::String> for $name {
            fn from(s: ::std::string::String) -> Self {
                Self(s)
            }
        }

        impl ::std::convert::From<&str> for $name {
            fn from(s: &str) -> Self {
                Self(s.to_string())
            }
        }

        impl ::std::cmp::PartialEq<str> for $name {
            fn eq(&self, other: &str) -> bool {
                self.0 == other
            }
        }

        impl ::std::cmp::PartialEq<&str> for $name {
            fn eq(&self, other: &&str) -> bool {
                self.0 == *other
            }
        }

        impl ::std::cmp::PartialEq<::std::string::String> for $name {
            fn eq(&self, other: &::std::string::String) -> bool {
                self.0 == *other
            }
        }

        impl ::std::borrow::Borrow<str> for $name {
            fn borrow(&self) -> &str {
                &self.0
            }
        }
    };
}

#[cfg(test)]
mod tests {
    // Exercise the macro end-to-end so every branch of the generated
    // impl block is live under `cargo test`.
    crate::define_id_newtype!(
        /// Fixture id type only used by these tests.
        TestId
    );

    #[test]
    fn construction_and_display() {
        let id = TestId::new("abc");
        assert_eq!(id.to_string(), "abc");
        assert_eq!(id.as_str(), "abc");
    }

    #[test]
    fn comparisons_against_str_family() {
        let id = TestId::new("abc");
        assert_eq!(id, *"abc");
        assert_eq!(id, "abc");
        assert_eq!(id, String::from("abc"));
    }

    #[test]
    fn hashmap_lookup_by_str_via_borrow() {
        use std::collections::HashMap;
        let mut m: HashMap<TestId, u32> = HashMap::new();
        m.insert(TestId::new("abc"), 7);
        // `Borrow<str>` enables the `&str` lookup.
        assert_eq!(m.get("abc").copied(), Some(7));
    }

    #[test]
    fn serde_roundtrips_as_bare_string() {
        let id = TestId::new("abc");
        let j = serde_json::to_string(&id).unwrap();
        assert_eq!(j, "\"abc\"");
        let parsed: TestId = serde_json::from_str(&j).unwrap();
        assert_eq!(parsed, id);
    }

    #[test]
    fn deref_gives_str_slice() {
        let id = TestId::new("hello world");
        assert!(id.starts_with("hello"));
    }
}
