//! MatchQueryIR — flat, structured-output-compatible subset of QueryIR.
//!
//! Covers ~95% of production graph queries (pattern matching with filters,
//! projections, aggregations, ordering). No recursive types — all structs
//! are flat, keeping JSON Schema property count well within the Bedrock/
//! Anthropic structured output limits (24 optional, 50 total).
//!
//! After LLM generation, validate and convert to [`QueryIR`] via [`MatchQueryIR::into_query_ir`].
//!
//! Design rationale:
//! - No `Box<T>` recursion → no schema inlining explosion
//! - No data-carrying tagged enums → no variant property merging issues
//! - Only string enums (`ConditionOp`, `AggFunction`) → 0 schema property cost
//! - Multiple conditions are implicitly AND'd → covers 95%+ of filter patterns

use schemars::JsonSchema;
use serde::Deserialize;

use crate::error::OxError;
use crate::query_ir::{
    AggFunction, ComparisonOp, Expr, GraphPattern, LogicalOp, OrderClause, Projection, QueryIR,
    QueryOp, SortDirection, StringOp, VarLength,
};
use crate::types::{Direction, PropertyValue, sanitize_variable};

// ---------------------------------------------------------------------------
// Top-level IR
// ---------------------------------------------------------------------------

/// Structured-output-compatible query IR for Match operations.
///
/// Generated by LLM via structured output (JSON Schema enforced),
/// then converted to `QueryIR` for compilation to Cypher/GQL.
#[derive(Debug, Clone, Deserialize, JsonSchema)]
pub struct MatchQueryIR {
    /// Node patterns to match
    pub nodes: Vec<NodePattern>,
    /// Relationship patterns connecting nodes
    #[serde(default)]
    pub relationships: Vec<RelationshipPattern>,
    /// Filter conditions (implicit AND between all conditions)
    #[serde(default)]
    pub conditions: Vec<Condition>,
    /// Patterns that must NOT exist in the graph (compiled to NOT EXISTS).
    /// Use for safety checks, conflict avoidance, and exclusion queries.
    #[serde(default)]
    pub exclude_patterns: Vec<ExcludePattern>,
    /// RETURN clause
    pub returns: Vec<ReturnClause>,
    /// GROUP BY fields (for aggregation queries)
    #[serde(default)]
    pub group_by: Vec<GroupField>,
    /// ORDER BY clauses
    #[serde(default)]
    pub order_by: Vec<SortClause>,
    /// LIMIT clause
    pub limit: Option<u32>,
    /// SKIP clause
    pub skip: Option<u32>,
}

// ---------------------------------------------------------------------------
// Pattern types (flat structs, no enums)
// ---------------------------------------------------------------------------

/// A node to match: `(variable:Label)`
#[derive(Debug, Clone, Deserialize, JsonSchema)]
pub struct NodePattern {
    /// Variable name (e.g., "p" for Product)
    pub variable: String,
    /// Node label — must match ontology exactly
    pub label: String,
}

/// A relationship between two node variables: `(source)-[:label]->(target)`
#[derive(Debug, Clone, Deserialize, JsonSchema)]
pub struct RelationshipPattern {
    /// Edge label — must match ontology exactly
    pub label: String,
    /// Source node variable (outgoing direction)
    pub source: String,
    /// Target node variable
    pub target: String,
    /// Optional edge variable for accessing edge properties
    pub variable: Option<String>,
    /// Variable-length path: minimum hops
    pub min_hops: Option<u32>,
    /// Variable-length path: maximum hops
    pub max_hops: Option<u32>,
}

/// A relationship pattern that must NOT exist in the graph.
///
/// Compiled to `WHERE NOT EXISTS { MATCH (source)-[:label]-(target) }`.
/// Use for safety validation, conflict avoidance, and exclusion queries —
/// patterns that are impossible in SQL without expensive NOT IN subqueries.
#[derive(Debug, Clone, Deserialize, JsonSchema)]
pub struct ExcludePattern {
    /// Relationship label to exclude (e.g., "CONFLICTS_WITH", "AGGRAVATES").
    pub relationship_label: String,
    /// Source node variable (must be declared in `nodes`).
    pub source: String,
    /// Target node variable (must be declared in `nodes`).
    pub target: String,
}

// ---------------------------------------------------------------------------
// Flat conditions (no recursion, no nesting)
// ---------------------------------------------------------------------------

/// A single filter predicate: `variable.field op value`.
///
/// Exactly one of `string_value`, `number_value`, or `bool_value` should be set
/// (except for `is_null`/`is_not_null` where none are needed, and `in_list`
/// which uses `list_values`).
#[derive(Debug, Clone, Deserialize, JsonSchema)]
pub struct Condition {
    /// Variable reference (e.g., "p")
    pub variable: String,
    /// Property name (e.g., "price")
    pub field: String,
    /// Comparison operator
    pub op: ConditionOp,
    /// String value (for eq, contains, starts_with, etc.)
    pub string_value: Option<String>,
    /// Numeric value (for eq, lt, gt, etc.) — works for both int and float
    pub number_value: Option<f64>,
    /// Boolean value
    pub bool_value: Option<bool>,
    /// List of string values (for in_list)
    #[serde(default)]
    pub list_values: Vec<String>,
}

/// Comparison/filter operator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum ConditionOp {
    Eq,
    Neq,
    Lt,
    Lte,
    Gt,
    Gte,
    Contains,
    StartsWith,
    EndsWith,
    InList,
    IsNull,
    IsNotNull,
}

/// Aggregation functions allowed in MatchQueryIR.
///
/// Restricted subset of [`AggFunction`] — excludes `collect` and `collect_list`
/// which return arrays instead of scalar values, breaking row-per-entity output.
/// The full `AggFunction` enum is available in QueryIR for the fallback path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum MatchAggFunction {
    Count,
    Sum,
    Avg,
    Min,
    Max,
}

impl From<MatchAggFunction> for AggFunction {
    fn from(f: MatchAggFunction) -> Self {
        match f {
            MatchAggFunction::Count => AggFunction::Count,
            MatchAggFunction::Sum => AggFunction::Sum,
            MatchAggFunction::Avg => AggFunction::Avg,
            MatchAggFunction::Min => AggFunction::Min,
            MatchAggFunction::Max => AggFunction::Max,
        }
    }
}

// ---------------------------------------------------------------------------
// Return / projection (flat struct with optional aggregate overlay)
// ---------------------------------------------------------------------------

/// A RETURN clause entry.
///
/// - Plain field: `variable="p", field=Some("name")` → `p.name`
/// - Whole variable: `variable="p", field=None` → `p`
/// - Aggregation: `variable="o", aggregate=Some(Count)` → `count(o)`
/// - Field aggregation: `variable="p", field=Some("price"), aggregate=Some(Avg)` → `avg(p.price)`
#[derive(Debug, Clone, Deserialize, JsonSchema)]
pub struct ReturnClause {
    /// Variable reference
    pub variable: String,
    /// Property name (None = whole variable)
    pub field: Option<String>,
    /// Output alias
    pub alias: Option<String>,
    /// Aggregation function (None = plain field/variable).
    /// Only count/sum/avg/min/max allowed — collect/collect_list are excluded
    /// from the schema to prevent LLM from generating them.
    pub aggregate: Option<MatchAggFunction>,
    /// DISTINCT flag for aggregation
    pub distinct: Option<bool>,
}

/// A GROUP BY entry.
#[derive(Debug, Clone, Deserialize, JsonSchema)]
pub struct GroupField {
    /// Variable reference
    pub variable: String,
    /// Property name
    pub field: String,
}

/// An ORDER BY entry.
#[derive(Debug, Clone, Deserialize, JsonSchema)]
pub struct SortClause {
    /// Field reference: "variable.field" (e.g., "p.price") or alias name (e.g., "total_count")
    pub field: String,
    /// Sort descending (false = ascending)
    pub descending: bool,
}

// ---------------------------------------------------------------------------
// Validation + Conversion
// ---------------------------------------------------------------------------

impl MatchQueryIR {
    /// Validate structural integrity before conversion.
    ///
    /// Checks:
    /// - At least one return clause
    /// - Every condition that requires a value has one
    /// - Every relationship references variables declared in nodes
    fn validate(&self) -> Result<(), OxError> {
        if self.nodes.is_empty() {
            return Err(OxError::Validation {
                field: "nodes".into(),
                message: "MatchQueryIR must have at least one node pattern".into(),
            });
        }

        if self.returns.is_empty() {
            return Err(OxError::Validation {
                field: "returns".into(),
                message: "MatchQueryIR must have at least one return clause".into(),
            });
        }

        let node_vars: std::collections::HashSet<&str> =
            self.nodes.iter().map(|n| n.variable.as_str()).collect();

        for (i, rel) in self.relationships.iter().enumerate() {
            if !node_vars.contains(rel.source.as_str()) {
                return Err(OxError::Validation {
                    field: format!("relationships[{i}].source"),
                    message: format!(
                        "Relationship source '{}' not found in node patterns. Declared nodes: {:?}",
                        rel.source,
                        node_vars.iter().collect::<Vec<_>>()
                    ),
                });
            }
            if !node_vars.contains(rel.target.as_str()) {
                return Err(OxError::Validation {
                    field: format!("relationships[{i}].target"),
                    message: format!(
                        "Relationship target '{}' not found in node patterns. Declared nodes: {:?}",
                        rel.target,
                        node_vars.iter().collect::<Vec<_>>()
                    ),
                });
            }
        }

        for (i, exclude) in self.exclude_patterns.iter().enumerate() {
            if !node_vars.contains(exclude.source.as_str()) {
                return Err(OxError::Validation {
                    field: format!("exclude_patterns[{i}].source"),
                    message: format!(
                        "Exclude pattern source '{}' not found in node patterns. Declared nodes: {:?}",
                        exclude.source,
                        node_vars.iter().collect::<Vec<_>>()
                    ),
                });
            }
            if !node_vars.contains(exclude.target.as_str()) {
                return Err(OxError::Validation {
                    field: format!("exclude_patterns[{i}].target"),
                    message: format!(
                        "Exclude pattern target '{}' not found in node patterns. Declared nodes: {:?}",
                        exclude.target,
                        node_vars.iter().collect::<Vec<_>>()
                    ),
                });
            }
        }

        // Mixed aggregation + non-aggregation without group_by collapses rows.
        // Note: collect/collect_list are prevented at the schema level —
        // MatchAggFunction only includes count/sum/avg/min/max.
        let has_aggregation = self.returns.iter().any(|r| r.aggregate.is_some());
        let has_non_agg = self.returns.iter().any(|r| r.aggregate.is_none());
        if has_aggregation && has_non_agg && self.group_by.is_empty() {
            return Err(OxError::Validation {
                field: "group_by".into(),
                message: "Mixed aggregation and non-aggregation returns require group_by. \
                         Without group_by, use either all plain fields OR all aggregations."
                    .into(),
            });
        }

        for (i, cond) in self.conditions.iter().enumerate() {
            // Condition variable must reference a declared node
            if !node_vars.contains(cond.variable.as_str()) {
                return Err(OxError::Validation {
                    field: format!("conditions[{i}].variable"),
                    message: format!(
                        "Condition variable '{}' not found in node patterns. Declared nodes: {:?}",
                        cond.variable,
                        node_vars.iter().collect::<Vec<_>>()
                    ),
                });
            }

            let needs_value = !matches!(cond.op, ConditionOp::IsNull | ConditionOp::IsNotNull);
            let value_count = cond.string_value.is_some() as u8
                + cond.number_value.is_some() as u8
                + cond.bool_value.is_some() as u8
                + (!cond.list_values.is_empty()) as u8;

            if needs_value && value_count == 0 {
                return Err(OxError::Validation {
                    field: format!("conditions[{i}]"),
                    message: format!(
                        "Condition on {}.{} with op {:?} requires a value (string_value, number_value, or bool_value)",
                        cond.variable, cond.field, cond.op
                    ),
                });
            }

            // Exactly one value field should be set (mutual exclusion).
            // Note: normalize_conditions() should have resolved most conflicts
            // before this point. This check catches any remaining edge cases.
            if needs_value && value_count > 1 {
                return Err(OxError::Validation {
                    field: format!("conditions[{i}]"),
                    message: format!(
                        "Condition on {}.{} has multiple value fields set — only one of string_value, number_value, bool_value, or list_values should be provided",
                        cond.variable, cond.field
                    ),
                });
            }
        }

        Ok(())
    }

    /// Normalize LLM-generated conditions: when multiple value fields are set
    /// on a condition (e.g., both string_value and list_values), resolve the
    /// ambiguity by keeping the most specific one. This avoids expensive fallback
    /// retries (2 additional LLM calls) for a common and harmless LLM output pattern.
    fn normalize_conditions(&mut self) {
        for cond in &mut self.conditions {
            let value_count = cond.string_value.is_some() as u8
                + cond.number_value.is_some() as u8
                + cond.bool_value.is_some() as u8
                + (!cond.list_values.is_empty()) as u8;

            if value_count > 1 {
                // Priority: list_values > string_value > number_value > bool_value
                if !cond.list_values.is_empty() {
                    cond.string_value = None;
                    cond.number_value = None;
                    cond.bool_value = None;
                } else if cond.string_value.is_some() {
                    cond.number_value = None;
                    cond.bool_value = None;
                } else if cond.number_value.is_some() {
                    cond.bool_value = None;
                }
            }
        }
    }

    /// Validate and convert to QueryIR.
    pub fn into_query_ir(mut self) -> Result<QueryIR, OxError> {
        self.normalize_conditions();
        self.validate()?;

        let mut patterns: Vec<GraphPattern> =
            Vec::with_capacity(self.nodes.len() + self.relationships.len());

        for node in &self.nodes {
            patterns.push(GraphPattern::Node {
                variable: node.variable.clone(),
                label: Some(node.label.clone()),
                property_filters: Vec::new(),
            });
        }

        for rel in &self.relationships {
            // Normalize var_length: single-hop, zero-hop, or nonsensical values → direct edge.
            // LLM commonly generates (0,0), (1,1), (null,null), or arbitrary large numbers
            // like (694,694) — all should be treated as direct single-hop edges.
            // Only intentional variable-length paths (e.g., *1..5 for network traversal)
            // should produce VarLength. Max reasonable depth is 10.
            const MAX_HOPS: u32 = 10;
            let min_h = rel.min_hops.filter(|&v| v <= MAX_HOPS);
            let max_h = rel.max_hops.filter(|&v| v <= MAX_HOPS);
            if rel.min_hops.is_some_and(|v| v > MAX_HOPS)
                || rel.max_hops.is_some_and(|v| v > MAX_HOPS)
            {
                tracing::warn!(
                    min_hops = ?rel.min_hops,
                    max_hops = ?rel.max_hops,
                    "Clamped variable-length hops to MAX_HOPS={MAX_HOPS}"
                );
            }
            // Ensure min <= max; swap if reversed
            let (min_h, max_h) = match (min_h, max_h) {
                (Some(mn), Some(mx)) if mn > mx => (Some(mx), Some(mn)),
                other => other,
            };
            let var_length = match (min_h, max_h) {
                (None, None) | (Some(0), Some(0)) | (Some(1), Some(1)) => None,
                (Some(0), None) => None,
                (min, max) => Some(VarLength {
                    min: min.map(|v| v as usize),
                    max: max.map(|v| v as usize),
                }),
            };
            // Sanitize "null" string → None (LLM sometimes emits "null" instead of null)
            let variable = rel
                .variable
                .as_deref()
                .and_then(sanitize_variable)
                .map(String::from);
            patterns.push(GraphPattern::Relationship {
                variable,
                label: Some(rel.label.clone()),
                source: rel.source.clone(),
                target: rel.target.clone(),
                direction: Direction::Outgoing,
                property_filters: Vec::new(),
                var_length,
            });
        }

        // Build filter from conditions + exclude_patterns (NOT EXISTS).
        let mut filter = conditions_to_filter(&self.conditions);
        for exclude in &self.exclude_patterns {
            let not_exists = Expr::Not {
                inner: Box::new(Expr::Exists {
                    pattern: Box::new(GraphPattern::Relationship {
                        variable: None,
                        label: Some(exclude.relationship_label.clone()),
                        source: exclude.source.clone(),
                        target: exclude.target.clone(),
                        direction: Direction::Both,
                        property_filters: Vec::new(),
                        var_length: None,
                    }),
                }),
            };
            filter = Some(match filter {
                Some(existing) => Expr::Logical {
                    left: Box::new(existing),
                    op: LogicalOp::And,
                    right: Box::new(not_exists),
                },
                None => not_exists,
            });
        }
        let projections: Vec<Projection> = self.returns.iter().map(return_to_projection).collect();

        let group_by: Vec<Projection> = self
            .group_by
            .iter()
            .map(|g| Projection::Field {
                variable: g.variable.clone(),
                field: g.field.clone(),
                alias: None,
            })
            .collect();

        let order_by: Vec<OrderClause> = self.order_by.iter().map(sort_to_order).collect();

        let qir = QueryIR {
            operation: QueryOp::Match {
                patterns,
                filter,
                projections,
                optional: false,
                group_by,
            },
            limit: self.limit.map(|v| v as usize),
            skip: self.skip.map(|v| v as usize),
            order_by,
        };
        qir.validate()?;
        Ok(qir)
    }
}

// ---------------------------------------------------------------------------
// Conversion helpers
// ---------------------------------------------------------------------------

/// Convert flat conditions to a nested Expr tree (chained with AND).
fn conditions_to_filter(conditions: &[Condition]) -> Option<Expr> {
    let exprs: Vec<Expr> = conditions.iter().filter_map(condition_to_expr).collect();

    match exprs.len() {
        0 => None,
        1 => Some(exprs.into_iter().next().unwrap()),
        _ => {
            let mut iter = exprs.into_iter();
            let first = iter.next().unwrap();
            Some(iter.fold(first, |acc, expr| Expr::Logical {
                left: Box::new(acc),
                op: LogicalOp::And,
                right: Box::new(expr),
            }))
        }
    }
}

fn condition_to_expr(c: &Condition) -> Option<Expr> {
    let prop = Expr::Property {
        variable: c.variable.clone(),
        field: Some(c.field.clone()),
    };

    match c.op {
        ConditionOp::IsNull => {
            return Some(Expr::IsNull {
                expr: Box::new(prop),
                negated: false,
            });
        }
        ConditionOp::IsNotNull => {
            return Some(Expr::IsNull {
                expr: Box::new(prop),
                negated: true,
            });
        }
        ConditionOp::InList => {
            let values: Vec<PropertyValue> = c
                .list_values
                .iter()
                .map(|s| PropertyValue::String(s.clone()))
                .collect();
            return Some(Expr::In {
                expr: Box::new(prop),
                values,
            });
        }
        _ => {}
    }

    let value = condition_value(c)?;

    match c.op {
        ConditionOp::Eq => Some(Expr::Comparison {
            left: Box::new(prop),
            op: ComparisonOp::Eq,
            right: Box::new(value),
        }),
        ConditionOp::Neq => Some(Expr::Comparison {
            left: Box::new(prop),
            op: ComparisonOp::Neq,
            right: Box::new(value),
        }),
        ConditionOp::Lt => Some(Expr::Comparison {
            left: Box::new(prop),
            op: ComparisonOp::Lt,
            right: Box::new(value),
        }),
        ConditionOp::Lte => Some(Expr::Comparison {
            left: Box::new(prop),
            op: ComparisonOp::Lte,
            right: Box::new(value),
        }),
        ConditionOp::Gt => Some(Expr::Comparison {
            left: Box::new(prop),
            op: ComparisonOp::Gt,
            right: Box::new(value),
        }),
        ConditionOp::Gte => Some(Expr::Comparison {
            left: Box::new(prop),
            op: ComparisonOp::Gte,
            right: Box::new(value),
        }),
        ConditionOp::Contains => Some(Expr::StringOp {
            left: Box::new(prop),
            op: StringOp::Contains,
            right: Box::new(value),
        }),
        ConditionOp::StartsWith => Some(Expr::StringOp {
            left: Box::new(prop),
            op: StringOp::StartsWith,
            right: Box::new(value),
        }),
        ConditionOp::EndsWith => Some(Expr::StringOp {
            left: Box::new(prop),
            op: StringOp::EndsWith,
            right: Box::new(value),
        }),
        // Already handled above
        ConditionOp::InList | ConditionOp::IsNull | ConditionOp::IsNotNull => unreachable!(),
    }
}

/// Extract the literal value from a Condition's value fields.
fn condition_value(c: &Condition) -> Option<Expr> {
    if let Some(s) = &c.string_value {
        return Some(Expr::Literal {
            value: PropertyValue::String(s.clone()),
        });
    }
    if let Some(n) = c.number_value {
        // Prefer Int for whole numbers
        let value = if n.fract() == 0.0 && n >= i64::MIN as f64 && n <= i64::MAX as f64 {
            PropertyValue::Int(n as i64)
        } else {
            PropertyValue::Float(n)
        };
        return Some(Expr::Literal { value });
    }
    if let Some(b) = c.bool_value {
        return Some(Expr::Literal {
            value: PropertyValue::Bool(b),
        });
    }
    None
}

fn return_to_projection(r: &ReturnClause) -> Projection {
    if let Some(func) = r.aggregate {
        // Aggregation projection
        let argument = match &r.field {
            Some(f) => Box::new(Projection::Field {
                variable: r.variable.clone(),
                field: f.clone(),
                alias: None,
            }),
            None => Box::new(Projection::Variable {
                variable: r.variable.clone(),
                alias: None,
            }),
        };
        Projection::Aggregation {
            function: func.into(),
            argument,
            alias: r
                .alias
                .clone()
                .unwrap_or_else(|| format!("{func:?}").to_lowercase()),
            distinct: r.distinct.unwrap_or(false),
        }
    } else {
        match &r.field {
            Some(f) => Projection::Field {
                variable: r.variable.clone(),
                field: f.clone(),
                alias: r.alias.clone(),
            },
            None => Projection::Variable {
                variable: r.variable.clone(),
                alias: r.alias.clone(),
            },
        }
    }
}

fn sort_to_order(s: &SortClause) -> OrderClause {
    let direction = if s.descending {
        SortDirection::Desc
    } else {
        SortDirection::Asc
    };

    // Parse "variable.field" or treat as alias
    let projection = if let Some((var, field)) = s.field.split_once('.') {
        Projection::Field {
            variable: var.to_string(),
            field: field.to_string(),
            alias: None,
        }
    } else {
        // Alias reference (e.g., "total_count")
        Projection::Variable {
            variable: s.field.clone(),
            alias: None,
        }
    };

    OrderClause {
        projection,
        direction,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn simple_ir() -> MatchQueryIR {
        MatchQueryIR {
            nodes: vec![NodePattern {
                variable: "p".into(),
                label: "Product".into(),
            }],
            relationships: vec![],
            conditions: vec![],
            exclude_patterns: vec![],
            returns: vec![ReturnClause {
                variable: "p".into(),
                field: None,
                alias: None,
                aggregate: None,
                distinct: None,
            }],
            group_by: vec![],
            order_by: vec![],
            limit: Some(25),
            skip: None,
        }
    }

    #[test]
    fn simple_match_converts() {
        let qir = simple_ir().into_query_ir().unwrap();
        assert!(matches!(qir.operation, QueryOp::Match { .. }));
        assert_eq!(qir.limit, Some(25));
    }

    #[test]
    fn conditions_chain_as_and() {
        let conditions = vec![
            Condition {
                variable: "p".into(),
                field: "price".into(),
                op: ConditionOp::Gt,
                string_value: None,
                number_value: Some(100.0),
                bool_value: None,
                list_values: vec![],
            },
            Condition {
                variable: "p".into(),
                field: "name".into(),
                op: ConditionOp::Contains,
                string_value: Some("retinol".into()),
                number_value: None,
                bool_value: None,
                list_values: vec![],
            },
        ];
        let filter = conditions_to_filter(&conditions);
        assert!(matches!(
            filter,
            Some(Expr::Logical {
                op: LogicalOp::And,
                ..
            })
        ));
    }

    #[test]
    fn aggregation_return_converts() {
        let ret = ReturnClause {
            variable: "o".into(),
            field: None,
            alias: Some("order_count".into()),
            aggregate: Some(MatchAggFunction::Count),
            distinct: Some(false),
        };
        let proj = return_to_projection(&ret);
        assert!(matches!(
            proj,
            Projection::Aggregation {
                function: AggFunction::Count,
                ..
            }
        ));
    }

    #[test]
    fn number_value_prefers_int() {
        let c = Condition {
            variable: "p".into(),
            field: "qty".into(),
            op: ConditionOp::Eq,
            string_value: None,
            number_value: Some(42.0),
            bool_value: None,
            list_values: vec![],
        };
        let expr = condition_value(&c).unwrap();
        match expr {
            Expr::Literal {
                value: PropertyValue::Int(42),
            } => {}
            other => panic!("expected Int(42), got: {other:?}"),
        }
    }

    #[test]
    fn sort_clause_parses_dot_notation() {
        let s = SortClause {
            field: "p.price".into(),
            descending: true,
        };
        let oc = sort_to_order(&s);
        assert!(
            matches!(oc.projection, Projection::Field { ref variable, ref field, .. } if variable == "p" && field == "price")
        );
        assert_eq!(oc.direction, SortDirection::Desc);
    }

    #[test]
    fn is_null_condition() {
        let c = Condition {
            variable: "p".into(),
            field: "deleted_at".into(),
            op: ConditionOp::IsNull,
            string_value: None,
            number_value: None,
            bool_value: None,
            list_values: vec![],
        };
        let expr = condition_to_expr(&c).unwrap();
        assert!(matches!(expr, Expr::IsNull { negated: false, .. }));
    }

    #[test]
    fn in_list_condition() {
        let c = Condition {
            variable: "p".into(),
            field: "country".into(),
            op: ConditionOp::InList,
            string_value: None,
            number_value: None,
            bool_value: None,
            list_values: vec!["Korea".into(), "Japan".into()],
        };
        let expr = condition_to_expr(&c).unwrap();
        assert!(matches!(expr, Expr::In { values, .. } if values.len() == 2));
    }

    #[test]
    fn var_length_relationship() {
        let mut ir = simple_ir();
        ir.nodes.push(NodePattern {
            variable: "b".into(),
            label: "Person".into(),
        });
        ir.nodes[0] = NodePattern {
            variable: "a".into(),
            label: "Person".into(),
        };
        ir.relationships.push(RelationshipPattern {
            label: "KNOWS".into(),
            source: "a".into(),
            target: "b".into(),
            variable: None,
            min_hops: Some(1),
            max_hops: Some(3),
        });
        ir.returns = vec![ReturnClause {
            variable: "b".into(),
            field: None,
            alias: None,
            aggregate: None,
            distinct: None,
        }];
        let qir = ir.into_query_ir().unwrap();
        if let QueryOp::Match { patterns, .. } = &qir.operation {
            let rel = &patterns[2];
            assert!(
                matches!(rel, GraphPattern::Relationship { var_length: Some(vl), .. } if vl.min == Some(1) && vl.max == Some(3))
            );
        } else {
            panic!("expected Match");
        }
    }

    // --- Validation tests ---

    #[test]
    fn rejects_empty_returns() {
        let mut ir = simple_ir();
        ir.returns = vec![];
        let err = ir.into_query_ir().unwrap_err();
        assert!(matches!(err, OxError::Validation { ref field, .. } if field == "returns"));
    }

    #[test]
    fn rejects_condition_without_value() {
        let mut ir = simple_ir();
        ir.conditions.push(Condition {
            variable: "p".into(),
            field: "price".into(),
            op: ConditionOp::Gt,
            string_value: None,
            number_value: None,
            bool_value: None,
            list_values: vec![],
        });
        let err = ir.into_query_ir().unwrap_err();
        assert!(matches!(err, OxError::Validation { ref field, .. } if field == "conditions[0]"));
    }

    #[test]
    fn allows_is_null_without_value() {
        let mut ir = simple_ir();
        ir.conditions.push(Condition {
            variable: "p".into(),
            field: "deleted_at".into(),
            op: ConditionOp::IsNull,
            string_value: None,
            number_value: None,
            bool_value: None,
            list_values: vec![],
        });
        let qir = ir.into_query_ir().unwrap();
        assert!(matches!(
            qir.operation,
            QueryOp::Match {
                filter: Some(_),
                ..
            }
        ));
    }

    #[test]
    fn rejects_relationship_with_unknown_source() {
        let mut ir = simple_ir();
        ir.relationships.push(RelationshipPattern {
            label: "PLACED".into(),
            source: "c".into(), // "c" not in nodes
            target: "p".into(),
            variable: None,
            min_hops: None,
            max_hops: None,
        });
        let err = ir.into_query_ir().unwrap_err();
        assert!(matches!(err, OxError::Validation { ref field, .. } if field.contains("source")));
    }

    #[test]
    fn rejects_in_list_with_empty_values() {
        let mut ir = simple_ir();
        ir.conditions.push(Condition {
            variable: "p".into(),
            field: "country".into(),
            op: ConditionOp::InList,
            string_value: None,
            number_value: None,
            bool_value: None,
            list_values: vec![], // empty!
        });
        let err = ir.into_query_ir().unwrap_err();
        assert!(matches!(err, OxError::Validation { ref field, .. } if field == "conditions[0]"));
    }

    #[test]
    fn normalizes_var_length_1_1_to_none() {
        let mut ir = simple_ir();
        ir.nodes.push(NodePattern {
            variable: "i".into(),
            label: "Ingredient".into(),
        });
        ir.relationships.push(RelationshipPattern {
            label: "HAS_INGREDIENT".into(),
            source: "p".into(),
            target: "i".into(),
            variable: Some("r".into()),
            min_hops: Some(1),
            max_hops: Some(1),
        });
        let qir = ir.into_query_ir().unwrap();
        if let QueryOp::Match { patterns, .. } = &qir.operation {
            let rel = &patterns[2];
            assert!(matches!(
                rel,
                GraphPattern::Relationship {
                    var_length: None,
                    ..
                }
            ));
        } else {
            panic!("expected Match");
        }
    }

    #[test]
    fn sanitizes_null_string_variable() {
        let mut ir = simple_ir();
        ir.nodes.push(NodePattern {
            variable: "b".into(),
            label: "Brand".into(),
        });
        ir.relationships.push(RelationshipPattern {
            label: "MADE_BY".into(),
            source: "p".into(),
            target: "b".into(),
            variable: Some("null".into()),
            min_hops: None,
            max_hops: None,
        });
        let qir = ir.into_query_ir().unwrap();
        if let QueryOp::Match { patterns, .. } = &qir.operation {
            let rel = &patterns[2];
            assert!(matches!(
                rel,
                GraphPattern::Relationship { variable: None, .. }
            ));
        } else {
            panic!("expected Match");
        }
    }

    #[test]
    fn rejects_mixed_agg_without_group_by() {
        let mut ir = simple_ir();
        ir.returns = vec![
            ReturnClause {
                variable: "p".into(),
                field: Some("name".into()),
                alias: None,
                aggregate: None,
                distinct: None,
            },
            ReturnClause {
                variable: "p".into(),
                field: None,
                alias: Some("total".into()),
                aggregate: Some(MatchAggFunction::Count),
                distinct: None,
            },
        ];
        let err = ir.into_query_ir().unwrap_err();
        assert!(matches!(err, OxError::Validation { ref field, .. } if field == "group_by"));
    }

    #[test]
    fn allows_pure_agg_without_group_by() {
        let mut ir = simple_ir();
        ir.returns = vec![ReturnClause {
            variable: "p".into(),
            field: None,
            alias: Some("total".into()),
            aggregate: Some(MatchAggFunction::Count),
            distinct: None,
        }];
        assert!(ir.into_query_ir().is_ok());
    }
}
