//! Ontology HTTP routes.
//!
//! Module layout:
//! - [`crud`]          — list, apply commands, suggest insights, enrich
//! - [`exchange`]      — normalize, export to multiple formats, OWL import
//! - [`verifications`] — element verification CRUD
//! - [`schema_ops`]    — reindex, audit vs live graph, adopt graph schema

mod crud;
mod exchange;
mod schema_ops;
mod verifications;

// Glob re-exports include the `__path_<fn>` symbols generated by `utoipa::path`,
// so the OpenApi macro can resolve them via `routes::ontology::<fn>`.
pub use crud::*;
pub use exchange::*;
pub use schema_ops::*;
pub use verifications::*;
